### ISSUE TITLE
No response error

### ISSUE THREAD

**Issue by anonymous-tech-user** [NorthernMan54/homebridge-tcc#101]
The thermostat keeps showing as no response and sometimes pressing on it refreshes and gives the temperature. I’ve looked at the logs and this is what I get when the issue occurs:
`ChangeThermostat Error: Error: ERROR: _UpdateThermostat %s
    at /usr/lib/node_modules/homebridge-tcc/lib/tcc.js:134:20
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`

**Comment by NorthernMan54** [comment]
Duplicate of #109
