### ISSUE TITLE
Constant No response- Not working

### ISSUE THREAD

**Issue by anonymous-tech-user** [NorthernMan54/homebridge-tcc#109]
After updating to iOS 15, the plugin doesn’t seem to work- constant no response.

**Comment by NorthernMan54** [comment]
Honeywell has rate limiters on their site that your hitting with the plugin.  Please make sure you are only running one copy of the plugin, and let things settle down for a bit it should start working.  I find in my setup that this occasionally occurs after restarting.

**Comment by anonymous-tech-user** [comment]
Yes, I only have one copy of the plugin and the refresh rate is set to the max time. I've also deleted and re-installed the plugin in case I had made some unknown change or setting but the problem still occurs. Perhaps Apple Home is automatically refreshing the status (like in Control Centre) and thus the plugin is hitting the rate limiter?

**Comment by NorthernMan54** [comment]
The only other thing might be incorrect password.

Refreshes from the home app etc won't trigger additional calls to the Honeywell site.

**Comment by anonymous-tech-user** [comment]
Hmm, okay, thank you for the insight. It seems even with resetting everything, the no response just keeps happening randomly. There are sometimes even no logs in home bridge (Debug logging is off) when all this happens. Is there anything I can try?

**Comment by thabandit007** [comment]
I was getting this error as well, however i realized that i am also using IFTTT, so that leads to no response due to too many logins in that timeframe.

**Comment by anonymous-tech-user** [comment]
As of now, I'm still getting the errors unfortunately. I've tried with a new linux distro and a new homebridge setup for a fresh start but I still get the No Response in HomeKit. There are also no logs associated with this in homebridge and the thermostat itself appears fine in the homebridge accessories pane. I can't seem to figure out any more than this or any way to fix it. Also, I believe when I installed the TCC plugin, I saw quite the bit of deprecation notices during the installation log window, would this be affecting the problem anyhow?

**Comment by ip-rob** [comment]
Just to confirm that I see this behavior as well. Restarting homebridge clears up the error so that suggests it is not related to a limit on the Honeywell side. I'm running IOS 15.2. What additional information can I capture and provide to assist?

**Comment by NorthernMan54** [comment]
Just a FYI for people with this issue, I also have the same issue with both of my TCC thermostats, where they have no response most of the time.  I have tried adjusting the refresh interval, with no luck.  I'm stumped

**Comment by ip-rob** [comment]
For what it is worth, I restarted homebridge 3 days ago and have had pretty good luck with the thermostat since then. There is only one time it was non-responsive, but generally it is showing up and working. Problems like these are never fun to try to find...maybe it was network related for me. No idea.

**Comment by ibogost** [comment]
I've been having this issue for some time, but just today I noticed that the devices do not report "no response" in the Mac Home app even when they do in the iOS one. I've also noticed that controlling one of the thermostats from Mac Home.app seems to make it "responsive" in iOS.

Perhaps related, perhaps not, the only error I see in homebridge-tcc logging is "ERROR: _UpdateThermostat InvalidSessionID"

**Comment by anonymous-tech-user** [comment]
Maybe a work-around that might solve the problem in the time being? Would it be possible to make a plugin that uses the thermostat from another service which works natively with Honeywell (Google Home, SmartThings, Alexa) and then ports the info over to HomeKit so as to avoid whatever limitations Honeywell might be imposing?

**Comment by NorthernMan54** [comment]
Many thanks to @atlcoder, he spent some time digging further into the 'no response' issue and he has a potential fix that should reduce the frequency of issues going forward.  If you want to try this out, I just published it as a `beta` release, and you can install it via the Homebridge UI.

**Comment by ibogost** [comment]
> Many thanks to @atlcoder, he spent some time digging further into the 'no response' issue and he has a potential fix that should reduce the frequency of issues going forward. If you want to try this out, I just published it as a `beta` release, and you can install it via the Homebridge UI.

Has your beta branch been verified and is it ready to release in main? I’m extremely appreciative at the prospect of a solution but also don’t want to mess with installing beta code on my homebridge.

**Comment by NorthernMan54** [comment]
Before publishing the beta as the main release, I’m waiting for more feedback from testers.  So it is likely a week or 2 before this gets published.

**Comment by thabandit007** [comment]
i’ve updated to the beta and have been on it for 1 week, have not seen the no response message since. seems good
