### ISSUE TITLE
F/C in HOOBS

### ISSUE THREAD

**Issue by JBryant915** [NorthernMan54/homebridge-tcc#112]
Is there a way to have the display of the thermostat in homebred/HOOBS display in Fahrenheit? I have changed the hub settings in HOOBS to Fahrenheit but the thermostat in the display still shows in Celsius. In HomeKit, it does show correctly in F. Thank you for your time and very nice plugin for these thermostats.

**Comment by NorthernMan54** [comment]
my understanding is that the display units is a local setting, HomeKit is Celsius internally
