### ISSUE TITLE
Can’t install/uninstall

### ISSUE THREAD

**Issue by ibogost** [NorthernMan54/homebridge-tcc#114]
homebridge-tcc didn’t update properly for some reason and since then I can’t uninstall or reinstall it.

Get this message on homebridge boot:
ERROR LOADING PLUGIN homebridge-tcc:
[16/03/2022, 19:12:07] Error: Could not locate the bindings file.

Then when I try to uninstall or reinstall:

npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /usr/local/lib/node_modules/homebridge-tcc
npm ERR! dest /usr/local/lib/node_modules/.homebridge-tcc-PAesRtv1
npm ERR! errno -39
npm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-tcc' -> '/usr/local/lib/node_modules/.homebridge-tcc-PAesRtv1'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-03-17T00_22_40_801Z-debug.log

Sorry if this is just a Homebridge issue and not a TCC issue, but I can’t tell. It’s also not clear how to recover.

**Comment by NorthernMan54** [comment]
The error message gives a clue to the issue

```
pm ERR! ENOTEMPTY: directory not empty, rename '/usr/local/lib/node_modules/homebridge-tcc' -> '/usr/local/lib/node_modules/.homebridge-tcc-PAesRtv1'
```

From the command line you could try

```
sudo rm -rf /usr/local/lib/node_modules/homebridge-tcc
sudo rm -rf /usr/local/lib/node_modules/.homebridge-tcc*
```

**Comment by ibogost** [comment]
Aha, the second rm I wasn’t doing. Thanks! ^__^
