### ISSUE TITLE
No Plugin was found for the platform TCC

### ISSUE THREAD

**Issue by jandagroup** [NorthernMan54/homebridge-tcc#115]
Hi, great plugin! 👏

However, recently I'm unable to get this plugin to work. On startup, I keep getting the error:

"No plugin was found for the platform "tcc" in your Config.json. Please make sure the corresponding plugin is installed correctly" 

I'm installing/configuring via Homebridge UI v4.49.0 and running Homebridge v1.5.0. 

This used to work for me for years and the only thing that has changed is an update to Homebridge ui and Homebridge. 

Please advise. 

Thanks!

**Comment by NorthernMan54** [comment]
Check the homebridge logs from startup, something is stopping the plugin from loading.

Have you tried just re-installing the TCC plugin?

**Comment by NorthernMan54** [comment]
Glad to hear that you got things working
