### ISSUE TITLE
MTcc BridgeERRORError loading plugin "homebridge-tcc"   PMTcc BridgeERRORCould not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by Tesla-P100FX** [NorthernMan54/homebridge-tcc#116]
I have tried on multiple times  to install. This is what i get in the log 

8/3/2022, 4:14:14 PMTcc Bridge starting
8/3/2022, 4:15:32 PMTcc BridgeConfiguration change
8/3/2022, 4:15:32 PMtccbridge stopping
8/3/2022, 4:15:38 PMTcc Bridge starting
8/3/2022, 4:15:54 PMTcc BridgeERRORError loading plugin "homebridge-tcc"
8/3/2022, 4:15:54 PMTcc BridgeERRORCould not locate the bindings file. Tried:
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/build/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/build/Debug/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/build/Release/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/out/Debug/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/Debug/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/out/Release/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/Release/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/build/default/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/compiled/16.16.0/linux/arm/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/addon-build/release/install-root/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/addon-build/debug/install-root/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/addon-build/default/install-root/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/lib/binding/node-v93-linux-arm/node_expat.node
8/3/2022, 4:15:54 PMTcc BridgeERRORError: Could not locate the bindings file. Tried:
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/build/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/build/Debug/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/build/Release/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/out/Debug/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/Debug/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/out/Release/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/Release/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/build/default/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/compiled/16.16.0/linux/arm/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/addon-build/release/install-root/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/addon-build/debug/install-root/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/addon-build/default/install-root/node_expat.node
 → /var/lib/hoobs/tccbridge/node_modules/node-expat/lib/binding/node-v93-linux-arm/node_expat.node
    at bindings (/var/lib/hoobs/tccbridge/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/var/lib/hoobs/tccbridge/node_modules/node-expat/lib/node-expat.js:4:34)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/lib/hoobs/tccbridge/node_modules/xml2json/lib/xml2json.js:1:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/var/lib/hoobs/tccbridge/node_modules/xml2json/lib/index.js:3:18)
8/3/2022, 4:15:54 PMTcc BridgeWARNINGNo plugins installed.
8/3/2022, 4:15:54 PMTcc BridgeLoading 1 platforms...
8/3/2022, 4:15:55 PMTcc BridgeBridge is running on port 51906.

**Comment by Tesla-P100FX** [comment]
![Install TCC](https://user-images.githubusercontent.com/68130459/182729719-d5464353-4546-4e34-8d57-2245f9a4950b.jpg)

**Comment by Tesla-P100FX** [comment]
![Install TCC](https://user-images.githubusercontent.com/68130459/182848266-8864d78e-3765-48e2-8e21-f3047dbf16ce.jpg)

**Comment by NorthernMan54** [comment]
Your screen shot is just warnings, and is normal

Is this the same as #102

**Comment by Tesla-P100FX** [comment]
i did the following command and my system is all up to date. sudo apt-get install build-essential

Node 16.16.0
Homebridge 1.5.0 

Still says  BridgeERRORCould not locate the bindings file.
                PMTcc BridgeWARNINGNo plugins installed.

**Comment by Tesla-P100FX** [comment]
I tried loading this morning and low and behold it created instance and is working.     Thank you
