### ISSUE TITLE
No devices created, please restart?

### ISSUE THREAD

**Issue by adonnan** [NorthernMan54/homebridge-tcc#117]
Is this a sign of too many attempts? I can log into mytotalconnectcomfort.com just fine.
Node.js 14.20.0 running on raspberrypi

> [20/08/2022, 20:31:07] Registering platform 'homebridge-tcc.tcc'
> [20/08/2022, 20:31:08] [Thermostat] Loaded homebridge-tcc v0.2.27 child bridge successfully
> [20/08/2022, 20:31:08] Loaded 0 cached accessories from cachedAccessories.0E10E6D94AAE.
> [20/08/2022, 20:31:09] [Thermostat] didFinishLaunching
> [20/08/2022, 20:31:09] Homebridge v1.5.0 (HAP v0.10.2) (Thermostat) is running on port 37119.
> [20/08/2022, 20:31:11] [Thermostat] Critical Error - No devices created, please restart.
> [20/08/2022, 20:31:11] [Thermostat] Error: AuthenticationFailed

> [20/08/2022, 15:22:08] [Thermostat] Critical Error - No devices created, please restart.
> [20/08/2022, 15:22:08] [Thermostat] Error: TooManyAttempt

Here is my config. Has worked fine in the past.

> {
>     "name": "Thermostat",
>     "username": "xxxxx@gmail.com",
>     "password": "xxxxx",
>     "refresh": 903,
>     "storage": "fs",
>     "_bridge": {
>         "username": "0E:10:E6:D9:4A:AE",
>         "port": 37119
>     },
>     "platform": "tcc"
> }

**Comment by jlg89** [comment]
Same issue here.
