### ISSUE TITLE
AuthenticationFailed error

### ISSUE THREAD

**Issue by jlg89** [NorthernMan54/homebridge-tcc#119]
homebridge-tcc 0.2.27
HOOBS 4.2.8 (homebridge 1.5.0, Node 16.17.0)

All I'm getting every 10 minutes is "pollDevices Error: AuthenticationFailed." Once every 6 hours or so I see a "TooManyAttempt" error. 

Username/password is correct for the Honeywell Home / Resideo login.

{
    "platform": "tcc",
    "name": "Resideo",
    "refresh": 600,
    "username": "......",
    "password": "......"
}

Debug log:

9/18/2022, 9:50:13 AMclimatecontrolbridge stopping
9/18/2022, 9:50:18 AMClimate Control Bridge starting
9/18/2022, 9:50:21 AMClimate Control BridgeLoaded plugin 'homebridge-tcc'
9/18/2022, 9:50:23 AMClimate Control BridgeLoading 1 platforms...
9/18/2022, 9:50:23 AMClimate Control BridgeLoading 1 platforms...
9/18/2022, 9:50:23 AMClimate Control BridgeResideodidFinishLaunching
9/18/2022, 9:50:23 AMClimate Control BridgeResideodidFinishLaunching
9/18/2022, 9:50:23 AMClimate Control BridgeERRORSun, 18 Sep 2022 14:50:23 GMT tcc-lib Setting up TCC component
9/18/2022, 9:50:23 AMClimate Control BridgeERRORSun, 18 Sep 2022 14:50:23 GMT tcc-lib Setting up TCC component
9/18/2022, 9:50:23 AMClimate Control BridgeERRORSun, 18 Sep 2022 14:50:23 GMT tcc-lib Queue: Working on item #1.  Size: 0  Pending: 0
9/18/2022, 9:50:23 AMClimate Control BridgeERRORSun, 18 Sep 2022 14:50:23 GMT tcc-lib Queue: Working on item #1.  Size: 0  Pending: 0
9/18/2022, 9:50:24 AMClimate Control BridgeBridge is running on port 51836.
9/18/2022, 9:50:24 AMClimate Control BridgeBridge is running on port 51836.
9/18/2022, 9:50:24 AMClimate Control BridgeResideoCritical Error - No devices created, please restart.
9/18/2022, 9:50:24 AMClimate Control BridgeResideoCritical Error - No devices created, please restart.
9/18/2022, 9:50:24 AMClimate Control BridgeResideoError: AuthenticationFailed
9/18/2022, 9:50:24 AMClimate Control BridgeResideoError: AuthenticationFailed

**Comment by NorthernMan54** [comment]
Any reason why all the log lines are duplicated ?

**Comment by jlg89** [comment]
Unknown. I figured maybe it just wanted me to think it was twice as important as the other plugins.

**Comment by NorthernMan54** [comment]
My initial thought is that it may be related to your issue of not being able to authenticate to TCC.  Would you have two copies of the config in your config.json ?

**Comment by jlg89** [comment]
It's in its own bridge within HOOBS, and I only see it defined once in the config.

**Comment by jlg89** [comment]
OK, hang on. Honeywell is pushing people from TCC to the "Resideo Smart Home" app & interface, which is not the same login. So, if you've already migrated, or if you're a new user & all you know is Resideo, my assumption is that it won't work with this plugin.

**Comment by NorthernMan54** [comment]
It only works with thermostats and logins from this site - https://mytotalconnectcomfort.com/portal/

**Comment by jlg89** [comment]
According to Honeywell/Resideo: "The Honeywell Home App name has changed to Resideo App as of June 22nd. If you currently have the app, there is no need to do anything or re-login. You will see the name switch after your app updates sometime following June 22nd, the icon and user interface will remain the same."

I spoke with Resideo tech support to try to get some answers. Thermostats that were originally added to TCC end up getting "migrated" to Resideo, but are still accessible in TCC. Newer thermostats are Resideo-only. It sounds like Honeywell is focusing more on commercial, Resideo more on residential, but there's quite a bit of overlap, and it's hard to tell where they're headed with the apps & web backend for the various products. At the end of the day, though, all of the thermostats work with the Resideo app, but only older stuff with TCC.

I had to do go back and find the original TCC account info, as I didn't initially configure the t-stats I'm working with. Using that account info in the plugin, it works. Go figure, right? Thankfully, the newer "Resideo-only" t-stats are HomeKit compatible, so I should be able to add those directly.
