### ISSUE TITLE
Using non-secure connection to api

### ISSUE THREAD

**Issue by jasonzondor** [NorthernMan54/homebridge-tcc#120]
Was looking through the code and noticed that we're connecting to the api via http instead of https.  Tested connecting to the api via https and basic tests worked.  I'll work on a PR this weekend.

**Comment by NorthernMan54** [comment]
???

https://github.com/NorthernMan54/homebridge-tcc/blob/7eae71d8637474f31a1e44a10931ada618ebbbab/lib/tcc.js#L18

**Comment by jasonzondor** [comment]
Lol... nevermind... coffee hadn't kicked in yet.  I was looking at the SOAP actions: 

https://github.com/NorthernMan54/homebridge-tcc/blob/7eae71d8637474f31a1e44a10931ada618ebbbab/lib/tcc.js#L105
