### ISSUE TITLE
Feature Request: Expose Outdoor Temperature Sensor within HomeKit

### ISSUE THREAD

**Issue by readylmay** [NorthernMan54/homebridge-tcc#130]
I currently have my config set to:

`sensors: "all",`

but I am not getting an additional HomeKit Accessory for outside temperature. Is that expected? Perhaps erroring out on the humidity value of 128 is causing the outside sensor not to be created? 

log:

> Wed, 08 Mar 2023 05:01:35 GMT tcc TccAccessory() THERMOSTAT InsideTemperature = true, adding sensor
> Wed, 08 Mar 2023 05:01:35 GMT tcc TccAccessory() THERMOSTAT InsideHumidity = true, adding sensor
> Wed, 08 Mar 2023 05:01:35 GMT tcc Invalid outside humidity value for THERMOSTAT(8230923)

**Comment by johnjensenish** [comment]
I can see in [the code](https://github.com/NorthernMan54/homebridge-tcc/blob/bfad48a/index.js#L63) that it is the case if the outdoor sensor does not provide a valid humidity reading, that neither temperature nor humidity sensors will be added.

**Comment by johnjensenish** [comment]
@nbolender Do you want to take a look at supporting this use case?

**Comment by nbolender** [comment]
@johnjensenish I can definitely fix this. Hopefully I will have time within the next week.
