### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by thechrisreese** [NorthernMan54/homebridge-tcc#132]
The poll devices "http/1.1 service un-available" bug has returned for me.

**Comment by readylmay** [comment]
https://tccna.honeywell.com/ws/MobileV2.asmx

is returning with 503 service unavailable.

**Comment by NorthernMan54** [comment]
I just looked at mine, and no current issues.  Is it possible that they where doing system maintenance ?

**Comment by thechrisreese** [comment]
Actually yes it came back up.

**Comment by NorthernMan54** [comment]
Tks
