### ISSUE TITLE
Can't install plug-in

### ISSUE THREAD

**Issue by frmoses** [NorthernMan54/homebridge-tcc#135]
Using Homebridge on MacOS Ventura. New install of Homebridge. Installing this plugin fails every time. I have used this plug-in for several years, but can't get it to install again on my fresh install of Homebridge. Any help would be much appreciated as I have 7 thermostats I was controlling with this. I'm not a developer, just an end user of Homebridge.

This is the list of errors at the end of the install:

> gyp ERR! configure error ify:googleapis: timing reifyNode:node_modules/homebridge-tcc/
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
> gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
> gyp ERR! System Darwin 22.4.0
> gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat
> gyp ERR! node -v v18.16.0
> gyp ERR! node-gyp -v v9.3.1
> gyp ERR! not ok 
> npm ERR! code 1
> npm ERR! path /usr/local/lib/node_modules/homebridge-tcc/node_modules/node-expat
> npm ERR! command failed
> npm ERR! command sh -c node-gyp rebuild
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/server/.npm/_logs/2023-05-22T21_07_23_338Z-debug-0.log
> 
> Operation failed. Please review log for details.

**Comment by NorthernMan54** [comment]
The install process uses node-gyp, which requires additional packages to be installed. https://github.com/nodejs/node-gyp.

**Comment by NorthernMan54** [comment]
You should be okay with those versions.
