### ISSUE TITLE
Lost all accessories after updating Node to 20.9.

### ISSUE THREAD

**Issue by jmfbk** [NorthernMan54/homebridge-tcc#140]
### Analysis

I used hb-service to upgrade Node to 20.9. TCC plug-in is still installed and my config file is still there. No accessories listed though. 

### Expected Behavior

My accessories are still listed. 

### Steps To Reproduce

- Update Node to 20.9. 
- Bounce homebridge service

### Logs

```markdown
No logs
```

### Configuration

```json
The only thing weird about my environment is that my Homebridge server is running on macOS 10.15.
```

### Environment

- OS: macOS 10.15
- Software:1.7.0
- Node:20.9
- npm:10.1.0

### Process Supervisor

hb-service

**Comment by NorthernMan54** [comment]
Anything is the logs?

Am thinking it may need a `npm rebuild`

**Comment by jmfbk** [comment]
D'oh. That was it. Sorry for the noise.
