### ISSUE TITLE
Merge with homebridge-evohome?

### ISSUE THREAD

**Issue by luc-ass** [NorthernMan54/homebridge-tcc#18]
Would you like to merge with my plugin? I think Wochenende could better maintain one complete plugin rather than two separate ones...

Does your plugin already include domestic hot water and emea_zones?

**Comment by luc-ass** [comment]
Hm. I can not log in TCC because of an european account... does that make sense?

**Comment by NorthernMan54** [comment]
Domestic hot water and emea zones aren't available via TCC, or if you look at it differently.  I'm coded against the TCC portal and you are coded against the evohome portal, and while both are similar in functionality, both are vastly different in functionality.   And are connected to different backends at honeywell.  Hence your not being able to login to TCC.

I look at the relationship between the plugins as parent and child, while I used your design pattern as a starting point at this point it is not feasible to merge them back.

**Comment by NorthernMan54** [comment]
I was thinking thru this further afterwards, and if we did merge, I think we would need to be based on two separate lib modules, one for TCC and one for evohome.   We would need to keep the function calls consistent
