### ISSUE TITLE
Device ID? RedLink Gateway Compatibility

### ISSUE THREAD

**Issue by kenderson** [NorthernMan54/homebridge-tcc#2]
HI @NorthernMan54  - Thanks for getting this started!

I have a RedLink Internet Gateway that connects my thermostat to TCC. As part of the configuration, there is a Device MAC ID and Device CRC. I've tried both of these, and they result in homebridge erroring out when I start it up (currently running lots of other stuff through homebridge - not a total noob to Homebridge :-) ). After thinking this through, I'm thinking you may not have built this to interact with the Honeywell RedLink Gateway, and are using a Wireless Thermostat?

Thanks Again!
Ken

**Comment by bwdeleeuw** [comment]
Hi Ken,

I found this yesterday, so here goes. Go to the Honeywell Total Connect Comfort website, log in and open your device. Now look in the address bar and you will see something like:

`https://mytotalconnectcomfort.com/portal/Device/Control/1234567`

The last part is your Device ID. Hope that helps

**Comment by kenderson** [comment]
@bwdeleeuw Thanks! That did the trick! I'll submit a PR to add this bit of goodness to the Readme file.

Thanks Again!

**Comment by NorthernMan54** [comment]
Tks Guys, I updated the readme with that snippet.

**Comment by gradyhouston** [comment]
Was this ever added to the README? I have this same exact scenario as @kenderson, but I'm not sure where I'd put the Device ID in the plugin config. I didn't see a PR for this and didn't see it mentioned anywhere in the README.

**Comment by NorthernMan54** [comment]
Since 2016 I have added auto device discovery and removed the need to add the device Id.  If your thermostat is not automatically discovered, it is not a Honeywell TCC thermostat.  And you need to use one of the other Honeywell thermostat plugins.

**Comment by gradyhouston** [comment]
Ah, got it. Thank you!
