### ISSUE TITLE
Support For RTH9580

### ISSUE THREAD

**Issue by devbymike** [NorthernMan54/homebridge-tcc#20]
Hey guys, hate to open an issue. I know it's not the proper channel or use. But neither of you have contact details for the project or on your profiles.

First **THANK YOU** for your work on this.

Second, I can confirm that this also works with my Honeywell RTH9580 - got it up and running this evening. 

Cheers.

**Comment by NorthernMan54** [comment]
Tks Mike for the report of success with the RTH9580, I will update the README with this.

Regarding contact details, that was a preference to avoid spam.  I do get notified by github when issues are raised, so the lack of a contact doesn't impact supporting the plugin.
