### ISSUE TITLE
getCurrentHeatingCoolingState is null

### ISSUE THREAD

**Issue by dbavatar** [NorthernMan54/homebridge-tcc#22]
Debug log as requested, deviceid's removed.

[12/30/2016, 10:21:08 PM] [Master Bedroom] Update Values Master Bedroom { success: true,
  deviceLive: true,
  communicationLost: false,
  latestData: 
   { uiData: 
      { DispTemperature: 71,
        HeatSetpoint: 69,
        CoolSetpoint: 75,
        DisplayUnits: 'F',
        StatusHeat: 0,
        StatusCool: 0,
        HoldUntilCapable: true,
        ScheduleCapable: true,
        VacationHold: 0,
        DualSetpointStatus: false,
        HeatNextPeriod: 2,
        CoolNextPeriod: 2,
        HeatLowerSetptLimit: 50,
        HeatUpperSetptLimit: 88,
        CoolLowerSetptLimit: 61,
        CoolUpperSetptLimit: 88,
        ScheduleHeatSp: 69,
        ScheduleCoolSp: 75,
        SwitchAutoAllowed: true,
        SwitchCoolAllowed: true,
        SwitchOffAllowed: true,
        SwitchHeatAllowed: true,
        SwitchEmergencyHeatAllowed: false,
        SystemSwitchPosition: 1,
        Deadband: 3,
        IndoorHumidity: 128,
        DeviceID: XXX,
        Commercial: false,
        DispTemperatureAvailable: true,
        IndoorHumiditySensorAvailable: false,
        IndoorHumiditySensorNotFault: true,
        VacationHoldUntilTime: 0,
        TemporaryHoldUntilTime: 0,
        IsInVacationHoldMode: false,
        VacationHoldCancelable: false,
        SetpointChangeAllowed: true,
        OutdoorTemperature: 31,
        OutdoorHumidity: 49,
        OutdoorHumidityAvailable: true,
        OutdoorTemperatureAvailable: true,
        DispTemperatureStatus: 0,
        IndoorHumidStatus: 128,
        OutdoorTempStatus: 0,
        OutdoorHumidStatus: 0,
        OutdoorTemperatureSensorNotFault: true,
        OutdoorHumiditySensorNotFault: true,
        CurrentSetpointStatus: 0,
        EquipmentOutputStatus: null },
     fanData: 
      { fanMode: null,
        fanModeAutoAllowed: false,
        fanModeOnAllowed: false,
        fanModeCirculateAllowed: false,
        fanModeFollowScheduleAllowed: false,
        fanIsRunning: null },
     hasFan: false,
     canControlHumidification: false,
     drData: 
      { CoolSetpLimit: null,
        HeatSetpLimit: null,
        Phase: -1,
        OptOutable: false,
        DeltaCoolSP: null,
        DeltaHeatSP: null,
        Load: null } },
  alerts: '\r\n\r\n' }
[12/30/2016, 10:21:08 PM] [Master Bedroom] Change Master Bedroom { deviceLive: true }
[12/30/2016, 10:21:08 PM] [Master Bedroom] Target temperature for Master Bedroom is 20.6°
[12/30/2016, 10:21:08 PM] [Master Bedroom] Current temperature of Master Bedroom is 21.7°
[12/30/2016, 10:21:08 PM] [Master Bedroom] getCurrentHeatingCoolingState is null Master Bedroom
[12/30/2016, 10:21:08 PM] [Master Bedroom] getTargetHeatingCooling is  1 Master Bedroom
[12/30/2016, 10:21:08 PM] [Master Bedroom] Cool Setpoint temperature of Master Bedroom is 23.9°
[12/30/2016, 10:21:08 PM] [Master Bedroom] Heat Setpoint temperature of Master Bedroom is 20.6°
[12/30/2016, 10:21:08 PM] [Master Bedroom] Update Values Bedroom 2 { success: true,
  deviceLive: true,
  communicationLost: false,
  latestData: 
   { uiData: 
      { DispTemperature: 69,
        HeatSetpoint: 69,
        CoolSetpoint: 75,
        DisplayUnits: 'F',
        StatusHeat: 0,
        StatusCool: 0,
        HoldUntilCapable: true,
        ScheduleCapable: true,
        VacationHold: 0,
        DualSetpointStatus: true,
        HeatNextPeriod: 33,
        CoolNextPeriod: 33,
        HeatLowerSetptLimit: 50,
        HeatUpperSetptLimit: 69,
        CoolLowerSetptLimit: 71,
        CoolUpperSetptLimit: 88,
        ScheduleHeatSp: 69,
        ScheduleCoolSp: 75,
        SwitchAutoAllowed: false,
        SwitchCoolAllowed: true,
        SwitchOffAllowed: true,
        SwitchHeatAllowed: true,
        SwitchEmergencyHeatAllowed: false,
        SystemSwitchPosition: 2,
        Deadband: 0,
        IndoorHumidity: 128,
        DeviceID: XXX,
        Commercial: false,
        DispTemperatureAvailable: true,
        IndoorHumiditySensorAvailable: false,
        IndoorHumiditySensorNotFault: true,
        VacationHoldUntilTime: 0,
        TemporaryHoldUntilTime: 0,
        IsInVacationHoldMode: false,
        VacationHoldCancelable: false,
        SetpointChangeAllowed: false,
        OutdoorTemperature: 31,
        OutdoorHumidity: 49,
        OutdoorHumidityAvailable: true,
        OutdoorTemperatureAvailable: true,
        DispTemperatureStatus: 0,
        IndoorHumidStatus: 128,
        OutdoorTempStatus: 0,
        OutdoorHumidStatus: 0,
        OutdoorTemperatureSensorNotFault: true,
        OutdoorHumiditySensorNotFault: true,
        CurrentSetpointStatus: 0,
        EquipmentOutputStatus: null },
     fanData: 
      { fanMode: null,
        fanModeAutoAllowed: false,
        fanModeOnAllowed: false,
        fanModeCirculateAllowed: false,
        fanModeFollowScheduleAllowed: false,
        fanIsRunning: null },
     hasFan: false,
     canControlHumidification: false,
     drData: 
      { CoolSetpLimit: null,
        HeatSetpLimit: null,
        Phase: -1,
        OptOutable: false,
        DeltaCoolSP: null,
        DeltaHeatSP: null,
        Load: null } },
  alerts: '\r\n\r\n' }
[12/30/2016, 10:21:08 PM] [Master Bedroom] Change Bedroom 2 { deviceLive: true }
[12/30/2016, 10:21:08 PM] [Master Bedroom] Target temperature for Bedroom 2 is 10°
[12/30/2016, 10:21:08 PM] [Master Bedroom] Current temperature of Bedroom 2 is 20.6°
[12/30/2016, 10:21:08 PM] [Master Bedroom] getCurrentHeatingCoolingState is null Bedroom 2
[12/30/2016, 10:21:08 PM] [Master Bedroom] getTargetHeatingCooling is  0 Bedroom 2
[12/30/2016, 10:21:08 PM] [Master Bedroom] getTemperatureDisplayUnits Living Room
[12/30/2016, 10:21:08 PM] [Master Bedroom] Temperature unit for Living Room is set to F
[12/30/2016, 10:21:08 PM] [Master Bedroom] Target temperature for Living Room is 20.6°
[12/30/2016, 10:21:08 PM] [Master Bedroom] Current temperature of Living Room is 21.7°
[12/30/2016, 10:21:08 PM] [Master Bedroom] getTargetHeatingCooling is  1 Living Room
[12/30/2016, 10:21:08 PM] [Master Bedroom] getCurrentHeatingCoolingState is null Living Room
[12/30/2016, 10:21:08 PM] [Master Bedroom] getCurrentHeatingCoolingState: Device not reachable
[12/30/2016, 10:21:08 PM] [Master Bedroom] Target temperature for Garage is 4.4°
[12/30/2016, 10:21:08 PM] [Master Bedroom] Current temperature of Garage is 12.2°
[12/30/2016, 10:21:08 PM] [Master Bedroom] getTargetHeatingCooling is  1 Garage
[12/30/2016, 10:21:08 PM] [Master Bedroom] getCurrentHeatingCoolingState is 0 Garage
[12/30/2016, 10:21:08 PM] [Master Bedroom] getCurrentHeatingCoolingState: Device not reachable
[12/30/2016, 10:21:08 PM] [Master Bedroom] getTargetHeatingCooling is  1 Upper Level
[12/30/2016, 10:21:08 PM] [Master Bedroom] getCurrentHeatingCoolingState is null Upper Level
[12/30/2016, 10:21:08 PM] [Master Bedroom] getCurrentHeatingCoolingState: Device not reachable
[12/30/2016, 10:21:08 PM] [Master Bedroom] Target temperature for Upper Level is 18.9°
[12/30/2016, 10:21:08 PM] [Master Bedroom] Current temperature of Upper Level is 21.7°
[12/30/2016, 10:21:08 PM] [Master Bedroom] getTemperatureDisplayUnits Garage
[12/30/2016, 10:21:08 PM] [Master Bedroom] Temperature unit for Garage is set to F
[12/30/2016, 10:21:08 PM] [Master Bedroom] Heat Setpoint temperature of Master Bedroom is 20.6°
[12/30/2016, 10:21:08 PM] [Master Bedroom] Target temperature for Master Bedroom is 20.6°
[12/30/2016, 10:21:08 PM] [Master Bedroom] getCurrentHeatingCoolingState is null Master Bedroom
[12/30/2016, 10:21:08 PM] [Master Bedroom] Cool Setpoint temperature of Master Bedroom is 23.9°
[12/30/2016, 10:21:08 PM] [Master Bedroom] Current temperature of Master Bedroom is 21.7°
[12/30/2016, 10:21:08 PM] [Master Bedroom] getTemperatureDisplayUnits Master Bedroom
[12/30/2016, 10:21:08 PM] [Master Bedroom] Temperature unit for Master Bedroom is set to F
[12/30/2016, 10:21:08 PM] [Master Bedroom] getTargetHeatingCooling is  1 Master Bedroom
[12/30/2016, 10:21:09 PM] [Master Bedroom] Update Values Upper Level { success: true,
  deviceLive: true,
  communicationLost: false,
  latestData: 
   { uiData: 
      { DispTemperature: 71,
        HeatSetpoint: 66,
        CoolSetpoint: 85,
        DisplayUnits: 'F',
        StatusHeat: 2,
        StatusCool: 0,
        HoldUntilCapable: true,
        ScheduleCapable: true,
        VacationHold: 0,
        DualSetpointStatus: true,
        HeatNextPeriod: 32,
        CoolNextPeriod: 32,
        HeatLowerSetptLimit: 50,
        HeatUpperSetptLimit: 69,
        CoolLowerSetptLimit: 71,
        CoolUpperSetptLimit: 88,
        ScheduleHeatSp: 55,
        ScheduleCoolSp: 85,
        SwitchAutoAllowed: false,
        SwitchCoolAllowed: true,
        SwitchOffAllowed: true,
        SwitchHeatAllowed: true,
        SwitchEmergencyHeatAllowed: false,
        SystemSwitchPosition: 1,
        Deadband: 0,
        IndoorHumidity: 128,
        DeviceID: XXX,
        Commercial: false,
        DispTemperatureAvailable: true,
        IndoorHumiditySensorAvailable: false,
        IndoorHumiditySensorNotFault: true,
        VacationHoldUntilTime: 0,
        TemporaryHoldUntilTime: 0,
        IsInVacationHoldMode: false,
        VacationHoldCancelable: false,
        SetpointChangeAllowed: true,
        OutdoorTemperature: 30,
        OutdoorHumidity: 49,
        OutdoorHumidityAvailable: true,
        OutdoorTemperatureAvailable: true,
        DispTemperatureStatus: 0,
        IndoorHumidStatus: 128,
        OutdoorTempStatus: 0,
        OutdoorHumidStatus: 0,
        OutdoorTemperatureSensorNotFault: true,
        OutdoorHumiditySensorNotFault: true,
        CurrentSetpointStatus: 2,
        EquipmentOutputStatus: null },
     fanData: 
      { fanMode: null,
        fanModeAutoAllowed: false,
        fanModeOnAllowed: false,
        fanModeCirculateAllowed: false,
        fanModeFollowScheduleAllowed: false,
        fanIsRunning: null },
     hasFan: false,
     canControlHumidification: false,
     drData: 
      { CoolSetpLimit: null,
        HeatSetpLimit: null,
        Phase: -1,
        OptOutable: false,
        DeltaCoolSP: null,
        DeltaHeatSP: null,
        Load: null } },
  alerts: '\r\n\r\n' }
[12/30/2016, 10:21:09 PM] [Master Bedroom] Change Upper Level { deviceLive: true }
[12/30/2016, 10:21:09 PM] [Master Bedroom] Target temperature for Upper Level is 18.9°
[12/30/2016, 10:21:09 PM] [Master Bedroom] Current temperature of Upper Level is 21.7°
[12/30/2016, 10:21:09 PM] [Master Bedroom] getCurrentHeatingCoolingState is null Upper Level
[12/30/2016, 10:21:09 PM] [Master Bedroom] getTargetHeatingCooling is  1 Upper Level
[12/30/2016, 10:21:09 PM] [Master Bedroom] Update Values Living Room { success: true,
  deviceLive: true,
  communicationLost: false,
  latestData: 
   { uiData: 
      { DispTemperature: 71,
        HeatSetpoint: 69,
        CoolSetpoint: 74,
        DisplayUnits: 'F',
        StatusHeat: 0,
        StatusCool: 0,
        HoldUntilCapable: true,
        ScheduleCapable: true,
        VacationHold: 0,
        DualSetpointStatus: true,
        HeatNextPeriod: 95,
        CoolNextPeriod: 2,
        HeatLowerSetptLimit: 50,
        HeatUpperSetptLimit: 72,
        CoolLowerSetptLimit: 72,
        CoolUpperSetptLimit: 88,
        ScheduleHeatSp: 69,
        ScheduleCoolSp: 74,
        SwitchAutoAllowed: false,
        SwitchCoolAllowed: true,
        SwitchOffAllowed: true,
        SwitchHeatAllowed: true,
        SwitchEmergencyHeatAllowed: false,
        SystemSwitchPosition: 1,
        Deadband: 0,
        IndoorHumidity: 128,
        DeviceID: XXX,
        Commercial: false,
        DispTemperatureAvailable: true,
        IndoorHumiditySensorAvailable: false,
        IndoorHumiditySensorNotFault: true,
        VacationHoldUntilTime: 0,
        TemporaryHoldUntilTime: 0,
        IsInVacationHoldMode: false,
        VacationHoldCancelable: false,
        SetpointChangeAllowed: true,
        OutdoorTemperature: 31,
        OutdoorHumidity: 49,
        OutdoorHumidityAvailable: true,
        OutdoorTemperatureAvailable: true,
        DispTemperatureStatus: 0,
        IndoorHumidStatus: 128,
        OutdoorTempStatus: 0,
        OutdoorHumidStatus: 0,
        OutdoorTemperatureSensorNotFault: true,
        OutdoorHumiditySensorNotFault: true,
        CurrentSetpointStatus: 0,
        EquipmentOutputStatus: null },
     fanData: 
      { fanMode: null,
        fanModeAutoAllowed: false,
        fanModeOnAllowed: false,
        fanModeCirculateAllowed: false,
        fanModeFollowScheduleAllowed: false,
        fanIsRunning: null },
     hasFan: false,
     canControlHumidification: false,
     drData: 
      { CoolSetpLimit: null,
        HeatSetpLimit: null,
        Phase: -1,
        OptOutable: false,
        DeltaCoolSP: null,
        DeltaHeatSP: null,
        Load: null } },
  alerts: '\r\n\r\n' }
[12/30/2016, 10:21:09 PM] [Master Bedroom] Change Living Room { deviceLive: true }
[12/30/2016, 10:21:09 PM] [Master Bedroom] Target temperature for Living Room is 20.6°
[12/30/2016, 10:21:09 PM] [Master Bedroom] Current temperature of Living Room is 21.7°
[12/30/2016, 10:21:09 PM] [Master Bedroom] getCurrentHeatingCoolingState is null Living Room
[12/30/2016, 10:21:09 PM] [Master Bedroom] getTargetHeatingCooling is  1 Living Room
[12/30/2016, 10:21:10 PM] [Master Bedroom] Update Values Garage { success: true,
  deviceLive: true,
  communicationLost: false,
  latestData: 
   { uiData: 
      { DispTemperature: 54,
        HeatSetpoint: 40,
        CoolSetpoint: 0,
        DisplayUnits: 'F',
        StatusHeat: 0,
        StatusCool: 0,
        HoldUntilCapable: true,
        ScheduleCapable: true,
        VacationHold: 0,
        DualSetpointStatus: true,
        HeatNextPeriod: 24,
        CoolNextPeriod: 0,
        HeatLowerSetptLimit: 40,
        HeatUpperSetptLimit: 90,
        CoolLowerSetptLimit: 50,
        CoolUpperSetptLimit: 99,
        ScheduleHeatSp: 40,
        ScheduleCoolSp: 82,
        SwitchAutoAllowed: false,
        SwitchCoolAllowed: false,
        SwitchOffAllowed: true,
        SwitchHeatAllowed: true,
        SwitchEmergencyHeatAllowed: false,
        SystemSwitchPosition: 1,
        Deadband: 0,
        IndoorHumidity: 128,
        DeviceID: XXX,
        Commercial: false,
        DispTemperatureAvailable: true,
        IndoorHumiditySensorAvailable: false,
        IndoorHumiditySensorNotFault: true,
        VacationHoldUntilTime: 0,
        TemporaryHoldUntilTime: 0,
        IsInVacationHoldMode: false,
        VacationHoldCancelable: false,
        SetpointChangeAllowed: true,
        OutdoorTemperature: 128,
        OutdoorHumidity: 128,
        OutdoorHumidityAvailable: false,
        OutdoorTemperatureAvailable: false,
        DispTemperatureStatus: 0,
        IndoorHumidStatus: 128,
        OutdoorTempStatus: 128,
        OutdoorHumidStatus: 128,
        OutdoorTemperatureSensorNotFault: true,
        OutdoorHumiditySensorNotFault: true,
        CurrentSetpointStatus: 0,
        EquipmentOutputStatus: 0 },
     fanData: 
      { fanMode: 0,
        fanModeAutoAllowed: true,
        fanModeOnAllowed: true,
        fanModeCirculateAllowed: false,
        fanModeFollowScheduleAllowed: false,
        fanIsRunning: false },
     hasFan: true,
     canControlHumidification: false,
     drData: 
      { CoolSetpLimit: null,
        HeatSetpLimit: null,
        Phase: -1,
        OptOutable: false,
        DeltaCoolSP: null,
        DeltaHeatSP: null,
        Load: null } },
  alerts: '\r\n\r\n' }
[12/30/2016, 10:21:10 PM] [Master Bedroom] Change Garage { deviceLive: true }
[12/30/2016, 10:21:10 PM] [Master Bedroom] Target temperature for Garage is 4.4°
[12/30/2016, 10:21:10 PM] [Master Bedroom] Current temperature of Garage is 12.2°
[12/30/2016, 10:21:10 PM] [Master Bedroom] getCurrentHeatingCoolingState is 0 Garage
[12/30/2016, 10:21:10 PM] [Master Bedroom] getTargetHeatingCooling is  1 Garage

**Comment by NorthernMan54** [comment]
When you use the TCC website, does it show when the system is running?

If it does, could you collect the debug output when it is running, I want to compare the two and see what variable it is using to return the status.

**Comment by dbavatar** [comment]
Yes TCC shows it running when it is. The output in the first post has a mix of running and not running, "Bedroom 2" should be off. SystemSwitchPosition perhaps?

**Comment by NorthernMan54** [comment]
I wasn't thinking when I posted that yesterday, in the log it shows what is changing in the responses from TCC no need for debug etc.   Just let it run for a while then look at the Change log entries, and pick out one from when the heat turns on.   This is from mine when the heat kicks in.

[1/1/2017, 3:03:00 PM] [Thermostat] updateValues 1
[1/1/2017, 3:03:01 PM] [Thermostat] Change Main Floor { latestData: { uiData: { EquipmentOutputStatus: 1 } } }

And it shows that EquipmentOutputStatus is changed when the heat kicks in.  What is changing in yours when the heat kicks in?

**Comment by dbavatar** [comment]
On Sun, Jan 1, 2017 at 3:49 PM, NorthernMan54 <notifications@github.com>
wrote:

> I wasn't thinking when I posted that yesterday, in the log it shows what
> is changing in the responses from TCC no need for debug etc. Just let it
> run for a while then look at the Change log entries, and pick out one from
> when the heat turns on. This is from mine when the heat kicks in.
>
> [1/1/2017, 3:03:00 PM] [Thermostat] updateValues 1
> [1/1/2017, 3:03:01 PM] [Thermostat] Change Main Floor { latestData: {
> uiData: { EquipmentOutputStatus: 1 } } }
>
> And it shows that EquipmentOutputStatus is changed when the heat kicks in.
> What is changing in yours when the heat kicks in?
>
> —
>


Heat -> Off
[1/2/2017, 10:46:53 PM] [Master Bedroom] Update Values Living Room {
success: true,
  deviceLive: true,
  communicationLost: false,
  latestData:
   { uiData:
      { DispTemperature: 71,
        HeatSetpoint: 69,
        CoolSetpoint: 74,
        DisplayUnits: 'F',
        StatusHeat: 0,
        StatusCool: 0,
        HoldUntilCapable: true,
        ScheduleCapable: true,
        VacationHold: 0,
        DualSetpointStatus: true,
        HeatNextPeriod: 95,
        CoolNextPeriod: 2,
        HeatLowerSetptLimit: 50,
        HeatUpperSetptLimit: 72,
        CoolLowerSetptLimit: 72,
        CoolUpperSetptLimit: 88,
        ScheduleHeatSp: 69,
        ScheduleCoolSp: 74,
        SwitchAutoAllowed: false,
        SwitchCoolAllowed: true,
        SwitchOffAllowed: true,
        SwitchHeatAllowed: true,
        SwitchEmergencyHeatAllowed: false,
        SystemSwitchPosition: 2,
        Deadband: 0,
        IndoorHumidity: 128,
        DeviceID: 518496,
        Commercial: false,
        DispTemperatureAvailable: true,
        IndoorHumiditySensorAvailable: false,
        IndoorHumiditySensorNotFault: true,
        VacationHoldUntilTime: 0,
        TemporaryHoldUntilTime: 0,
        IsInVacationHoldMode: false,
        VacationHoldCancelable: false,
        SetpointChangeAllowed: false,
        OutdoorTemperature: 41,
        OutdoorHumidity: 65,
        OutdoorHumidityAvailable: true,
        OutdoorTemperatureAvailable: true,
        DispTemperatureStatus: 0,
        IndoorHumidStatus: 128,
        OutdoorTempStatus: 0,
        OutdoorHumidStatus: 0,
        OutdoorTemperatureSensorNotFault: true,
        OutdoorHumiditySensorNotFault: true,
        CurrentSetpointStatus: 0,
        EquipmentOutputStatus: null },
     fanData:
      { fanMode: null,
        fanModeAutoAllowed: false,
        fanModeOnAllowed: false,
        fanModeCirculateAllowed: false,
        fanModeFollowScheduleAllowed: false,
        fanIsRunning: null },
     hasFan: false,
     canControlHumidification: false,
     drData:
      { CoolSetpLimit: null,
        HeatSetpLimit: null,
        Phase: -1,
        OptOutable: false,
        DeltaCoolSP: null,
        DeltaHeatSP: null,
        Load: null } },
  alerts: '\r\n\r\n' }
[1/2/2017, 10:46:53 PM] [Master Bedroom] Change Living Room { latestData: {
uiData: { SystemSwitchPosition: 2, SetpointChangeAllowed: false } } }
[1/2/2017, 10:46:53 PM] [Master Bedroom] Target temperature for Living Room
is 10°
[1/2/2017, 10:46:53 PM] [Master Bedroom] Current temperature of Living Room
is 21.7°
[1/2/2017, 10:46:53 PM] [Master Bedroom] getCurrentHeatingCoolingState is
null Living Room
[1/2/2017, 10:46:53 PM] [Master Bedroom] getTargetHeatingCooling is  0
Living Room

Off-> Heat & hold temp 67F until 11:45pm.

[1/2/2017, 10:48:53 PM] [Master Bedroom] Update Values Living Room {
success: true,
  deviceLive: true,
  communicationLost: false,
  latestData:
   { uiData:
      { DispTemperature: 71,
        HeatSetpoint: 67,
        CoolSetpoint: 74,
        DisplayUnits: 'F',
        StatusHeat: 1,
        StatusCool: 0,
        HoldUntilCapable: true,
        ScheduleCapable: true,
        VacationHold: 0,
        DualSetpointStatus: true,
        HeatNextPeriod: 95,
        CoolNextPeriod: 2,
        HeatLowerSetptLimit: 50,
        HeatUpperSetptLimit: 72,
        CoolLowerSetptLimit: 72,
        CoolUpperSetptLimit: 88,
        ScheduleHeatSp: 69,
        ScheduleCoolSp: 74,
        SwitchAutoAllowed: false,
        SwitchCoolAllowed: true,
        SwitchOffAllowed: true,
        SwitchHeatAllowed: true,
        SwitchEmergencyHeatAllowed: false,
        SystemSwitchPosition: 1,
        Deadband: 0,
        IndoorHumidity: 128,
        DeviceID: 518496,
        Commercial: false,
        DispTemperatureAvailable: true,
        IndoorHumiditySensorAvailable: false,
        IndoorHumiditySensorNotFault: true,
        VacationHoldUntilTime: 0,
        TemporaryHoldUntilTime: 1425,
        IsInVacationHoldMode: false,
        VacationHoldCancelable: false,
        SetpointChangeAllowed: true,
        OutdoorTemperature: 41,
        OutdoorHumidity: 65,
        OutdoorHumidityAvailable: true,
        OutdoorTemperatureAvailable: true,
        DispTemperatureStatus: 0,
        IndoorHumidStatus: 128,
        OutdoorTempStatus: 0,
        OutdoorHumidStatus: 0,
        OutdoorTemperatureSensorNotFault: true,
        OutdoorHumiditySensorNotFault: true,
        CurrentSetpointStatus: 1,
        EquipmentOutputStatus: null },
     fanData:
      { fanMode: null,
        fanModeAutoAllowed: false,
        fanModeOnAllowed: false,
        fanModeCirculateAllowed: false,
        fanModeFollowScheduleAllowed: false,
        fanIsRunning: null },
     hasFan: false,
     canControlHumidification: false,
     drData:
      { CoolSetpLimit: null,
        HeatSetpLimit: null,
        Phase: -1,
        OptOutable: false,
        DeltaCoolSP: null,
        DeltaHeatSP: null,
        Load: null } },
  alerts: '\r\n\r\n' }
[1/2/2017, 10:48:53 PM] [Master Bedroom] Change Living Room { latestData:
   { uiData:
      { HeatSetpoint: 67,
        StatusHeat: 1,
        SystemSwitchPosition: 1,
        TemporaryHoldUntilTime: 1425,
        SetpointChangeAllowed: true,
        CurrentSetpointStatus: 1 } } }
[1/2/2017, 10:48:53 PM] [Master Bedroom] Target temperature for Living Room
is 19.4°
[1/2/2017, 10:48:53 PM] [Master Bedroom] Current temperature of Living Room
is 21.7°
[1/2/2017, 10:48:53 PM] [Master Bedroom] getCurrentHeatingCoolingState is
null Living Room
[1/2/2017, 10:48:53 PM] [Master Bedroom] getTargetHeatingCooling is  1
Living Room

**Comment by NorthernMan54** [comment]
I see what you are saying about SystemSwitchPosition, in the plugin this is already mapped to the "Mode" screen in the Home App.   Take a look at below, and see the "Heat is on" on the right side.  For me this appears when the furnace is running, and producing heat.  Do you have something similar on yours?  


![heat on](https://cloud.githubusercontent.com/assets/19808920/21625979/94281a92-d1dc-11e6-9ab7-8f3dfff44ea5.jpg)

**Comment by dbavatar** [comment]
On Tue, Jan 3, 2017 at 6:21 PM, NorthernMan54 <notifications@github.com>
wrote:

> I see what you are saying about SystemSwitchPosition, in the plugin this
> is already mapped to the "Mode" screen in the Home App. Take a look at
> below, and see the "Heat is on" on the right side. For me this appears when
> the furnace is running, and producing heat. Do you have something similar
> on yours?—
>
> Only on the "Garage" thermostat. The other 4 drive inverter heat pumps,
there really isn't an "on" state, but they can switch from heating to
cooling, if in auto mode. Not sure there is an indication of that, but I
don't use auto mode because it tends to oscillate between heating and
cooling.

**Comment by NorthernMan54** [comment]
Okay, I think we can close this then.  You will find for your Garage that it will say Heating in the home app when it is producing heat.
