### ISSUE TITLE
Error at Login to Honeywell site

### ISSUE THREAD

**Issue by MADempsey** [NorthernMan54/homebridge-tcc#24]
Hey There.  I have been struggling to get my Homebridge instance to work with my Honeywell VisionPro 8000 (TH8321WF1001).  I get an error at start-up that says:  

[Thermostat] Error during Login: TypeError: this.devices.map is not a function

I suppose it could be that the Honeywell device does not support management by this Homebridge module, it almost seems (in my limited knowledge) that it is a Java Script error?
This device is capable to be managed with the Total Connect website, the TCC app from the apple store, and my Logitech Harmony Home device.  
I am able to start and stop activities from Homebridge (with the Harmony Hub module) so it appears that Homebridge itself is working.  
Thanks for any help you can give me!

**Comment by NorthernMan54** [comment]
That error appears to be related to the config.json entry and the "devices" item.  When the plugin is reading the devices item, it is causing the error.  Please ensure that you are following the syntax from the sample.

**Comment by MADempsey** [comment]
The sample had multiple devices, while I only have 1 (at present).  I added the brackets that I thought were not necessary, and the problem is resolved.  Thanks for the quick response!
