### ISSUE TITLE
international site login

### ISSUE THREAD

**Issue by djsomi** [NorthernMan54/homebridge-tcc#25]
Hi,

I'm using the international site of the my totalconnect comfort. I got error messages regarding that the plugin cannot login.  So I've modified the url in the tcc.js, but it is still cannot login. 

I get 
"TCC Login Failed, can't connect to TCC Web Site { Error: Hostname/IP doesn't match certificate's altnames: "Host: mytotalconnectcomfort.com. is not in the cert's altnames: DNS:*.azurewebsites.net, DNS:*.scm.azurewebsites.net, DNS:*.azure-mobile.net, DNS:*.scm.azure-mobile.net""

international url:
https://international.mytotalconnectcomfort.com/

Can you please help me to solve this problem? Maybe an option will be handy in the HB config file.

Many Thanks
Zoltan

**Comment by NorthernMan54** [comment]
@djsomi That sounds like a great idea, we could add an option for the international version.   If you wanted to fork the code base and make the changes then submit a pull request that would be great.

For the actual error, if you have properly captured the URL's then it would a defect in nodejs ;(.  But I think you may have an incorrect URL, hence the issue.   To capture the URL's I used firefox with the firebug plugin and watched which URL's and data that was passed back and forth from the TCC website.   And wrote the flow based on that.

**Comment by djsomi** [comment]
Thanks for your reply, I've chceked the urls, and I did not see any other url than 

https://international.mytotalconnectcomfort.com/

**Comment by NorthernMan54** [comment]
@djsomi I looked a little bit deeper, and the URL's used by the international site are totally different than the north american site.  

North America Login Page

https://mytotalconnectcomfort.com/portal/

International Login Page

https://international.mytotalconnectcomfort.com/api/accountApi/login

To make the plugin work with the international site, it would take a major rework of the plugin and not just a simple url change.  Have you tried the other Honeywell plugin?

**Comment by djsomi** [comment]
Which one do you suggest? To be honest I did not find any other.

**Comment by NorthernMan54** [comment]
I have seen one called evohome, which I used as a base for my plugin.   If they don't work you could fork my version and update it with the correct url's for the international version.   When I made this version, I had used Firefox with the firebug plugin and figured out the url's and data the website was expecting.  The plugin emulates a user accessing the website, as there was no published api for the thermostat.  It took a fair bit of effort as I needed to follow the flow thru the website, and send responses similar to a browser.

If the changes aren't that significant we could merge the 2 and have an option for the international version.
