### ISSUE TITLE
Upgraded from 0.22 to 0.27 and now Device is unreachable

### ISSUE THREAD

**Issue by gsulshski** [NorthernMan54/homebridge-tcc#27]
I was using a prior version (I believe is was 0.22) of home bridge-tcc and it seemed to be working for a couple of weeks.  I decided to check to see if there were updates and noticed that there was a new version.  When I updated ,  I got the following error that the Device is not reachable has shown below.  In this case,  I don't have the thermostat on.  If turn the thermostat on,  the device state seems to be tracking (on, temperature set, etc) still remains unreachable.

[Thermostat] getTemperatureDisplayUnits Main Floor
[Thermostat] Temperature unit for Main Floor is set to F
 [Thermostat] Target temperature for Main Floor is 20.6°
 [Thermostat] Current temperature of Main Floor is 20.6°
 [Thermostat] getTargetHeatingCooling is  0 Main Floor
[Thermostat] getCurrentHeatingCoolingState is 0 Main Floor
 [Thermostat] getCurrentHeatingCoolingState: Device not reachable
 [Thermostat] getCurrentHeatingCoolingState is 0 Main Floor
[Thermostat] getCurrentHeatingCoolingState: Device not reachable

**Comment by NorthernMan54** [comment]
I was looking at the code, and this is a problem with changes introduced with version .27.  I was making minor tweaks for the next version of homebridge, and broke this.

It's going to be a week before I can fix it, in the mean time you should able to install version .26 and be okay.

**Comment by gsulshski** [comment]
I went back to 0.26 and that works!
Looking forward to your updates when you are ready.

**Comment by NorthernMan54** [comment]
Tks I'm glad to hear it works okay.  Once I'm back from vacation I should be to fix it within a few days.

**Comment by NorthernMan54** [comment]
I have fixed the underlying issue.   You should be okay to update to the latest version.

**Comment by gsulshski** [comment]
I upgraded to 0.28 and it worked.

BTW: I am using a Honeywell TH6320WF thermostat

You could add that to your tested list if you wish.

**Comment by NorthernMan54** [comment]
Tks, just added it.  It will appear with the next update
