### ISSUE TITLE
SystemSwitchPosition : 5

### ISSUE THREAD

**Issue by l3nticular** [NorthernMan54/homebridge-tcc#28]
Thanks for writing this!

I'm seeing SystemSwitchPosition becoming 5 on the TCC site, which is causing homebridge-tcc to mark the system as off.  I'm not sure why/how this is happening; I see heat as 1, off as 2, cool as 3, and auto as 4.  After another refresh, it returned 5 (through my browser's dev tools).

After attempting to reproduce methodically for the issue, I was unable to.

I'm wondering if others have also seen this, and perhaps value 5 needs to be mapped to something or be ignored entirely.

**Comment by NorthernMan54** [comment]
I haven't seen a 5 with my setup.  What does the thermostat show when it is 5?

**Comment by l3nticular** [comment]
I'm almost always using "Auto" with fan in "Follow Schedule" mode, so it's generally that.  I'll try to see if it can come up any other way.  It's a pretty easy hack for me to re-map this myself, but I'd prefer to figure out what's going on.
![systemswitch_5](https://user-images.githubusercontent.com/11479790/29804154-92eb0662-8c35-11e7-8162-52e012c124ad.png)

**Comment by l3nticular** [comment]
Just to be clear, putting it into that config doesn't generate the switch=5 right away.

**Comment by l3nticular** [comment]
I should've just checked the TCC web site sources in the first place.  Here are the enums:
      
  // system switch enumeration - use with ModelProperty.systemSwitchPosition
        my.SystemSwitch = { EMHEAT: 0, HEAT: 1, OFF: 2, COOL: 3, AUTOHEAT: 4, AUTOCOOL: 5, SOUTHERN_AWAY: 6, UNKNOWN: 7 };

So, 0+1 => Heat, 2 => Off, 3 => Cool, 4+5 => Auto.
6 => seems to be a humidity control only, not temperature control so it could be either cool or off.
(src: https://customer.honeywell.com/resources/techlit/TechLitDocuments/69-0000s/69-1816EFS.pdf)
0 => is "Emergency Heat" (from same PDF), so probably just mark as heat.

**Comment by dbavatar** [comment]
> 6 => seems to be a humidity control only, not temperature control so it could be either cool or off.

I have temperature control in mode 7, which on the physical display is called "Drying". Although it appears to shut down temperature control, this is not true.  My system seems to aim for 4F under setpoint (versus 2F under during COOL), which is either the setpoint immediately before entering drying mode, or the set at any time without changing mode from the web/app. "Cool" could be appropriate to display if there is no good alternative.

My thermostat is an MHK1.

**Comment by l3nticular** [comment]
Ah I have the 9850 series.  I'll update the merge request to include 7 as cool.  I think the mode 6 "southern away" can also run the cooling (my thermostat doesn't support this mode, as far as I can tell), but it might be better to be 'off'.

**Comment by NorthernMan54** [comment]
Tks

This is a great bit of research on the functionality.  Once your done testing your changes let me know and I will publish the update.

**Comment by NorthernMan54** [comment]
I just published this to NPM.  Tis
