### ISSUE TITLE
Unable to verify first certificate? 

### ISSUE THREAD

**Issue by thechrisreese** [NorthernMan54/homebridge-tcc#30]
C Login Failed, can't connect to TCC Web Site { Error: unable to verify the first certificate                                
    at TLSSocket.<anonymous> (_tls_wrap.js:1098:38)                                                                            
    at emitNone (events.js:105:13)                                                                                             
    at TLSSocket.emit (events.js:207:7)                                                                                        
    at TLSSocket._finishInit (_tls_wrap.js:628:8)                                                                              
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:458:38) code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE' }                             
[2017-9-5 13:31:02] [Thermostat] Error during Login: TCC Login failed, can't connect to TCC Web Site

**Comment by ayanm00** [comment]
I'm having the same issue. Strangely the online Total Connect Comfort wasn't working, but the app was working just fine. Now they are both up and running, but I'm still getting that error.

**Comment by ayanm00** [comment]
*wasn't working last night

**Comment by NorthernMan54** [comment]
And I just checked my setup, and I have the same issue ;-(

And after checking further, it seems they are using a different cert provider that isn't widely shared.  I get this from wget on my mac

wget https://mytotalconnectcomfort.com/portal/
--2017-09-05 19:00:24--  https://mytotalconnectcomfort.com/portal/
Resolving mytotalconnectcomfort.com... 199.62.84.100
Connecting to mytotalconnectcomfort.com|199.62.84.100|:443... connected.
ERROR: cannot verify mytotalconnectcomfort.com's certificate, issued by ‘CN=DigiCert SHA2 High Assurance Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US’:
  Unable to locally verify the issuer's authority.
To connect to mytotalconnectcomfort.com insecurely, use `--no-check-certificate'.


To workaround the issue, I removed the certificate check.  Please reinstall

**Comment by gsulshski** [comment]
I had the same problem.  Unable to verify first certificate.

I updated to 0.0.30 and I was able to run correctly.

Can you clarify what it means to remove the certificate check.  Just curious.

**Comment by thechrisreese** [comment]
Yeah it’s working now with the update. I am also curious what the change means.

**Comment by ayanm00** [comment]
I'm also glad to report that it's working again! Also, this may be the wrong place to ask this, but does anyone else have a thing where when you open the Home app it shows "Updating..." on all accessories for at least 45 seconds? This is most visible on an iPad that I have the home shared to, in which opening Control Center shows "Updating..." for at least 45 seconds. Thanks for fixing the issue! This is my most used HomeBridge plugin.

**Comment by NorthernMan54** [comment]
To workaround the issue, I told the plugin https/ssl layer not to check SSL certificates for validity.  So the plugin just trusts the website.  This is needed for the foreseeable future until the digitcert.com <http://digitcert.com/> cert prodvider is added to the nodejs ssl certs.   The workaround only impacts the connection from the plugin, and does not change any other settings on your computer.

**Comment by NorthernMan54** [comment]
@ayanm00 As the developer, I'm actually surprised I didn't see it first ;-) But as we have our heat and cooling currently turned off, I'm not surprised.

For your 45 seconds of updating.  That is likely to be related to the number of accessories you have, and the coding of the plugins itself.  In my environment access remotely it takes about 8 seconds for updating to complete
