### ISSUE TITLE
Set temperature incorrect with homebridge v0.4.28

### ISSUE THREAD

**Issue by JimDog546** [NorthernMan54/homebridge-tcc#31]
After updating from homebridge v0.4.19 to homebridge v0.4.28 the set temperature in my Home app sometimes does not match the set temperature on my thermostat.  I believe this is due to either a rounding or decimal to integer issue with the celsius to fahrenheit conversion, but oddly the current temperature at the same value is displaying correctly.  I am not sure if the problem resides in homebridge or the homebridge-tcc plugin.

For example, Home is reporting that my thermostat's current temperature is 74 degrees and it is set to 73 degrees:

![img_1316](https://user-images.githubusercontent.com/32178686/30717952-6faa67e6-9eec-11e7-9e85-41010791cc4c.PNG)

However both values are actually 74 degrees as displayed in the Honeywell app:

![img_1318](https://user-images.githubusercontent.com/32178686/30717960-7559d992-9eec-11e7-849b-ad42abfcf9fb.PNG)

Other values such as 70 degrees display correctly which is what makes me think it's a rounding or decimal to integer issue because 70F = 21.1111C and 21C = 69.8F (rounded up to 70), but 74F = 23.3333C and 23C = 73.4F (rounded down to 73).

I am using the latest version of homebridge-tcc (0.0.31).  This issue is not present when using the plugin with homebridge v0.4.19 but is present when using the plugin with homebridge v0.4.28.

**Comment by NorthernMan54** [comment]
I know changes were made in the latest version of homebridge regarding the values passed between plugins and HomeKit to ensure that they were valid from homekits view.  And I think this is likely to be cause.

In the plugin I’m working to one digit of precision and HomeKit is strictly Celsius.

This is the conversion formula from Celsius to Fahrenheit.

((temperature * 9 / 5) + 32).toFixed(1)

Let me dig into this further, it may require a homebridge update to resolve.

**Comment by JimDog546** [comment]
I did incremental upgrades to homebridge to try to determine when this issue started.  The set temperature works properly with homebridge versions 0.4.19 through 0.4.22.  This issues starts with version 0.4.23 and is present in every subsequent version through the current 0.4.28.  Hopefully that helps to track down what's causing it.

**Comment by NorthernMan54** [comment]
Tks for the troubleshooting on versions of homebridge, that has helped a lot.   I added some additional debugging to the plugin to help troubleshoot this.  I was wondering if you could update the homebridge-tcc to the latest version.  Then start homebridge in DEBUG mode and share the log file while recreating the issue.  To start homebridge in DEBUG mode I usually use this.  YMMV

DEBUG=* homebridge

If you normally start homebridge with other options, please include them.

**Comment by ayanm00** [comment]
Hi everyone,
I'd just like to report that I am facing this issue as well. For the time being, I have downgraded to an older version of HomeBridge, and it's working great. Hope it gets fixed soon. Thanks!

**Comment by NorthernMan54** [comment]
@ayanm00

I’m still looking for a debug log showing the error to fix the issue, if you could collect and share one, much appreciated.

**Comment by ayanm00** [comment]
@NorthernMan54 

Sure, whatever helps. How do I turn on debugging?

**Comment by NorthernMan54** [comment]
Start homebridge with this command line

DEBUG=* homebridge

It will generate a lot of logging, what’s important is what is logged when the temperature is incorrectly displayed.

**Comment by ayanm00** [comment]
@NorthernMan54 

Okay, I have to update HomeBridge first, and then I'll start debug mode. How long should I leave it running like that? Should I try to replicate the issue?

**Comment by NorthernMan54** [comment]
Until you can replicate the issue, I need the values from the logs to fix the issue.

**Comment by ayanm00** [comment]
@NorthernMan54 

Okay, the issue happens basically every time so it shouldn't be hard to replicate. Where's the log file located? Sorry for all the questions; I'm tech savvy, but I'm not a programmer.

**Comment by ayanm00** [comment]
@NorthernMan54 

I did some analysis of my own, and I found that, at least on my thermostat, only certain temperatures are having this issue. Going from any temperature, at least in cool mode, to 55, 56, 57, 58, 64, 65, 66, 67, 73, 74, 75, 76, 82, 83, 84, 85, 91, 92, 93, or 94 results in that temperature correctly being set on the thermostat itself, but the displayed temperature in the Home app goes down by 1 degree. Here is a screenshot of the temperatures sorted by place value. The pattern is very interesting. Hope this helps! I'll send the debug log once I learn where it's located. Thanks!

![thermostat](https://user-images.githubusercontent.com/31669016/31754964-d4fc21be-b460-11e7-943f-1f70829cfda9.jpg)

**Comment by NorthernMan54** [comment]
If you start from the command line, the debug log is displayed on the console/screen.

**Comment by ayanm00** [comment]
@NorthernMan54 

Here is part of the debug log. I just set the temperature to 76, which is one with the issue, and copied the output after that. 

[Debug.pdf](https://github.com/NorthernMan54/homebridge-tcc/files/1399881/Debug.pdf)

**Comment by NorthernMan54** [comment]
@ayanm00 Thanks for that, but unfortunately it doesn't have the error section.  When you are setting temperature, one of the messages in the section should be

Setting target temperature for XX

There will be a bit of back and forth with homekit in this section, which will include the actual values passed back and forth that I need to debug the issue.

What makes this challenging, is that the Home app is showing Temperature in Fahrenheit,  converting that to Celsius inside HomeKit, and I'm converting that to Fahrenheit to send to your thermostat.

**Comment by ayanm00** [comment]
@NorthernMan54 

Okay, sorry about that. I was confused what to copy because it was showing debugging from other plugins as well. I got a second MacBook and setup a fresh copy of Homebridge on it with just one thermostat in the config to make it easier to copy the debug log. I set the temperature to 76, and copied everything that appeared after I did so. 

[Debug 2.pdf](https://github.com/NorthernMan54/homebridge-tcc/files/1400899/Debug.2.pdf)

**Comment by NorthernMan54** [comment]
Okay, I see the problem, homebridge is dropping the decimal when display.

This is setting the temperature

Accessory [SecondHomebridge] Setting Characteristic "Target Temperature" to value 24.5 +1ms
[10/20/2017, 1:02:31 AM] [Thermostat] Setting target temperature for Upstairs to 24.5°
tcc toTCC 24.5 76.1 +16s
tcc toTCC 24.5 76.1 +0ms
[10/20/2017, 1:02:31 AM] [Thermostat] setHeatCoolSetpoint Upstairs 1 1
tcc setHeatCoolSetpoint {"DeviceID": 81247,"SystemSwitch":null,"CoolSetpoint":"76.1","HeatNextPeriod":null, "CoolNextPeriod":null,"StatusHeat":1,"StatusCool":1,"FanMode":null}

HomeKit gives me 24.5 as the setpoint point, and I tell your thermostat 76.1

This is reading the temperature

{ uiData: { CoolSetpoint: 76 } } }
 tcc toHB 76 24.4 +5ms
tcc toHB 24.4 +0ms
[10/20/2017, 1:02:33 AM] [Thermostat] Target temperature for Upstairs
is 24.4°
EventedHTTPServer [::ffff:192.168.0.46] Sending HTTP event '2.13' with data: {"characteristics":[{"aid":2,"iid":13,"value":24}]} +406ms

And what I send back the data, the thermostat tells me 76, I tell homebridge 24.4, but homebridge tells HomeKit 24, dropping the decimal.

Let me look at what is happening in homebridge with this.

**Comment by ayanm00** [comment]
@NorthernMan54 

Any news?

**Comment by NorthernMan54** [comment]
@ayanm00 I have been looking into this and trying to locate where the issue lies within homebridge/hap-nodejs with no luck yet. As I'm Canadian my whole system is set to Celsius, and have been trying to avoid changing everything to Fahrenheit to troubleshoot it further.   And it looks like I'm going to have to.

**Comment by ayanm00** [comment]
@NorthernMan54 

Sorry about that. Is there anything I can do to help? If you need any more information, please don't hesitate to ask!

**Comment by JimDog546** [comment]
This started with homebridge 0.4.23.  In that version hap-nodejs was upgraded from 0.4.27 to 0.4.28.  v0.4.28 of hap-nodejs included these changes: https://github.com/KhaosT/HAP-NodeJS/commit/30f0aadc1613863e1590a6132484da92e617e385.  I'm not a programmer/coder so I could be off base, but there was code added to lib/Characteristic.js, specifically Characteristic.prototype.validateValue beginning at line 172, that appears to try to validate values.  The numeric validation beginning at line 242 appears to try to do some decimal rounding or truncation.  I suspect that's where the problem is occurring.

**Comment by NorthernMan54** [comment]
@jimdoug456

You must be looking over my shoulder, as that is the exact place I’m looking as well.  I’m trying to figure out why 24.4 gets trimmed to 24.  But I haven’t been able to recreate the issue yet. In my test environment it is passing 24.4 to HomeKit.

As I had been playing with code all over the place, I’m going to go back to the release versions and start again.

**Comment by NorthernMan54** [comment]
Gentleman,

I think I have resolved the issue, if you could install the latest version of the homebridge-tcc plugin and the latest homebridge and try again, it should be fixed.

Before fix

 Accessory [Bart] Got Characteristic "Target Temperature" value: 24 +0ms

After fix

 Accessory [Bart] Got Characteristic "Target Temperature" value: 24.4 +1ms

As my system is in celsius I can't fully test, but I based on the details supplied by @ayanm00 this was the issue.

**Comment by ayanm00** [comment]
@NorthernMan54 @JimDog546 

After a few tries, it seems to be working perfectly. I'll let you all know if I see any more issues. Thank you so much for your work!
