### ISSUE TITLE
Doesn't Show All Thermostats

### ISSUE THREAD

**Issue by jvmahon** [NorthernMan54/homebridge-tcc#32]
I have 6 Honeywell thermostats, but the tcc plugin will only show a maximum of 4.  It used to show them all, but something has changed. I've tried deleting the plugin, as well as the persist / accessories data and restarting (tried several times), but to no avail.  Even did an entire new setup on a second Raspberry Pi. The startup info. suggests that the plugin recognizes all 6 thermostats, but then only 4 appear in HomeKit.  It isn't a logical pattern - it doesn't seem to follow the order of the thermostat listings in the config.json, but if I rearrange the listings sometimes I get a different set of 4.  I'm running the latest plugin / homekit server / nodejs.  I think this only recently started (about a month ago, all worked fine). Anybody else see this behavior?

**Comment by NorthernMan54** [comment]
After thinking about this further, I’m wondering if the problem is related to the iOS 11 updates made to Homebridge.  Have you updated to the latest homebridge?

**Comment by jvmahon** [comment]
yes, I'm on the latest updates of homebridge  and node. Thanks.

**Comment by NorthernMan54** [comment]
I did a quick trial with my setup, and I didn't see the same issue.

![img_1657](https://user-images.githubusercontent.com/19808920/32683868-b205ccb6-c64c-11e7-805e-859e3131a9b9.PNG)

**Comment by NorthernMan54** [comment]
I'm thinking you may need to share your config.json and tcc login so I can try it on my side.

**Comment by jvmahon** [comment]
O.K. - I'm trying to figure out - is there a way to send a private message using GitHub or can you send a email to me at jvm33@columbia.edu that I can respond to? I don't want to send the login publicly. Thanks for the help.

**Comment by NorthernMan54** [comment]
@jvmahon This for sharing, I tried it from my machine, and it worked okay.  See below.  But the timeout errors are a bit troubling, so I increased the timeout from 15 to 30 seconds.  Please reinstall homebridge-tcc, and try again.  And please include a log file.

![img_1670](https://user-images.githubusercontent.com/19808920/32704505-2f617420-c7d4-11e7-98e5-6fd9d26dd3e5.png)

**Comment by jvmahon** [comment]
Thanks.

I’ll give this a try.

In the meantime, I switched from Homebridge on a Raspberry Pi to HomeBridge on Windows and it all worked fine.
