### ISSUE TITLE
Honeywell Global Guard

### ISSUE THREAD

**Issue by jannnfe** [NorthernMan54/homebridge-tcc#34]
Hey,
do you have any ideas to bring my Honeywell Global Guard Security System into homebridge?
There is a Webinterface for arming and disarming: https://globalguard.friedland.co.uk
I would love to control my Security System with Siri :)
Thanks

**Comment by NorthernMan54** [comment]
You could take the same approach I took with this plugin, and have the plugin pretend to be a browser on the website and screen scrape the site.  It takes a bit of effort to determine what the various web requests are, but should be do-able.
