### ISSUE TITLE
Unable to set temp to 65

### ISSUE THREAD

**Issue by ayanm00** [NorthernMan54/homebridge-tcc#35]
Hi again @NorthernMan54,

I'm having an issue where I can't set my temperature to 65 (it goes up to 66 if I do). Any way I can help solve this again?

Thanks,
@ayanm00

**Comment by NorthernMan54** [comment]
A debug level with the setting change would be helpful in debugging.   I’m out of the country for the next week, and will be able to look at this further when I return.
