### ISSUE TITLE
Does not load the thermostat

### ISSUE THREAD

**Issue by johnh618** [NorthernMan54/homebridge-tcc#36]
I installed the tcc plugin to my homebridge running on my Synology DSM. It is not connecting to honeywell and communicating with my thermostat.

I have setup the config.json and when I run homebridge and look in the log I see that it loads 0 accessories and it says 
"Logged into tcc! undefined"
"Error during Login: TypeError: Cannot read property 'map' of undefined"

![image](https://user-images.githubusercontent.com/35173669/34642078-1c0754d8-f2d3-11e7-8fe1-22009b1ed23b.png)

Am I doing something wrong?  The only thing I have setup with my config.json is the thermostat.

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "..redacted...",
        "port": 51826,
        "pin": "..redacted..."
    },

    "description": "This is an example",

    "accessories": [
    ],

    "platforms": [
    	{
            "platform": "tcc",
            "name" : "Thermostat",
            "username" : "..redacted...",
            "password" : "..redacted...",
            "deviceID": "..redacted...",
            "debug": "True"
        }
    ]
}
```

-John

**Comment by NorthernMan54** [comment]
@johnh618 It looks like your config.json is incorrect.  The devices/deviceID section needs to look like the sample.  As you only have 1 device, just a single deviceID line is needed.

```
       {
            "platform": "tcc",
            "name" : "Thermostat",
            "username" : ".....",
            "password" : ".....",
            "devices" : [
                  {"deviceID": "1234567","name": "Other Floor"}
          	]
        },
```

**Comment by johnh618** [comment]
Thanks! Got it working last night.
