### ISSUE TITLE
Thermostats now show 154 degrees

### ISSUE THREAD

**Issue by JimBobSD** [NorthernMan54/homebridge-tcc#37]
After upgrading to the latest release of homebridge-tcc, my thermostats jumped from 72 degrees to 154 degrees as the current temperature.  

NM54, thanks for all your help on these plugins.  I use this one and your Alexa plugin.

**Comment by NorthernMan54** [comment]
Any chance you can send a debug log, showing the temperature being returned?

DEBUG=* homebridge

Thanks for sharing what your using, the Alexa one is my family’s favourite

**Comment by Hackashaq666** [comment]
Here too, lookd like the F conversion is broken again in this release, like it was several months ago.

**Comment by NorthernMan54** [comment]
I found the issue, and just published a fix.  Please update and try again

**Comment by Hackashaq666** [comment]
v0.1.2 fixes temp display.  Thank you for the useful plugin!
