### ISSUE TITLE
Temperature Unit

### ISSUE THREAD

**Issue by envoys** [NorthernMan54/homebridge-tcc#39]
In Home Kit, the temp is in Fahrenheit but Siri is in Celsius.

Is there anyway that this can be changed?

**Comment by NorthernMan54** [comment]
Sorry, temperature units is not controlled in the plugin, but on your phone.  The plugin only sends Celsius.

**Comment by Stuart-Richards** [comment]
Not sure if this is exactly related but I had a similar issue. In HomeKit the icon was showing Celsius even when I selected Fahrenheit. I realized I had been playing around in the Weather app and had changed the display there from Fahrenheit to Celsius. When I changed that option in the weather app back to Fahrenheit it changed in HomeKit too!
