### ISSUE TITLE
can't stay on permanent hold

### ISSUE THREAD

**Issue by ualymerej** [NorthernMan54/homebridge-tcc#43]
I generally keep my thermostat on permanent hold. Every time I use homekit to make temperature changes, it switches to a temporary hold which makes my temperature changes irregular since I don't have a schedule set. Am I doing something wrong or is there a way to make it so that it stays on permanent hold when I change the temperature?

**Comment by ualymerej** [comment]
Do you think it's an easy modification to the plugin I could do for my own usage?

**Comment by NorthernMan54** [comment]
That is how I got started with this, I took something that almost did what I wanted to do and made it do what I wanted.  This particular plugin I used someone else’s as a base to get started.

**Comment by ualymerej** [comment]
I understand that; I was just hoping for a starting point, but I guess you're just telling me the plugin itself is my starting point.

**Comment by gitlabiche** [comment]
I’m just gonna “upvote” here for existing plugin behavior along with schedule works great.  I also for permanent changes go to the Honeywell app.

Thx Northern Man

**Comment by ualymerej** [comment]
I understand that as it is implemented now, it works for many of you, but for people with less predictable schedules who are in and out of their house at irregular times, the option for permanent holds would make more sense. It would also give you the ability to actually use the homekit features to a greater extent. Homekit can use location services to detect if everyone is out of the house and can then automatically raise the temperature while you're out. It can detect when you're coming back and can set to cool. So far, it sounds like you're just using it the same way you'd be using the TCC app; to make occasional changes without actually walking to the thermostat, but there is so much more Homekit itself can do with the integration.

**Comment by Infallibleman** [comment]
Hello,

I have the same issue with my set up as well, that it reverts to "temporary" hold when I make a chance via the homekit using this plugin.  Is there a way to provide that as an option in the plugin setup, to choose either "temporary" or "permanent" hold?  that way, it won't need to be part of the hard coding, but can use what the end user selected as part of their setup?

Thanks!!

**Comment by NorthernMan54** [comment]
This has been implemented by @hakusaro and is available in version 0.1.7
