### ISSUE TITLE
How to implement storage option

### ISSUE THREAD

**Issue by gsulshski** [NorthernMan54/homebridge-tcc#46]
I noticed that you released a storage option about 7 months ago but I am not sure how to implement this option.  Can you update the readme or maybe I missed how this is implemented somewhere else ?

**Comment by NorthernMan54** [comment]
Greg,

The storage option is the backend for this

https://github.com/simont77/fakegato-history <https://github.com/simont77/fakegato-history>

And the code defaults to storing it to the local filesystem, so no need to do anything unless you wanted to use googledrive

Have you tried using the Elgato Eve App, you can see some pretty graphs etc

**Comment by NorthernMan54** [comment]
This is my config, and it works

{
    "platform": "tcc",
    "name": "Thermostat",
    "username": “XXXXXX@yahoo.ca",
    "password": “XXXXXX",
    "devices": [{
      "deviceID": “XXXXX",
      "name": "Living Room"
    }]
  }
