### ISSUE TITLE
Honeywell Home

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [NorthernMan54/homebridge-tcc#50]
Hey,

Just wondering if you could make this plugin to work with honeywell home(lyric) thermostats. I don’t know how to code that well, and I know that Honeywell has a website for their Honeywell Home api (https://developer.honeywell.com/). Just wondering if you could make this support their other thermostats too?

**Comment by NorthernMan54** [comment]
Unfortunately not, as developing the plugin would require having that thermostat.
