### ISSUE TITLE
Login failure due to Terms and Conditions Page

### ISSUE THREAD

**Issue by NorthernMan54** [NorthernMan54/homebridge-tcc#52]
[9/23/2019, 5:17:56 PM] [Thermostat] Logged into tcc! [ { deviceID: '2077898', name: 'Living Room' } ]
  tcc Device { Redirect: '/portal/Home/TermsAndConditions' } +0ms
[9/23/2019, 5:17:56 PM] [Thermostat] Adding TCC Device Living Room 2077898
[9/23/2019, 5:17:56 PM] [Thermostat] Initializing platform accessory 'Living Room'...
[9/23/2019, 5:17:56 PM] [Thermostat] getServices Living Room
(node:7890) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'uiData' of undefined
    at tccAccessory.getServices (/Users/sgracey/Code/homebridge-tcc/index.js:402:32)
    at Server._createAccessory (/Users/sgracey/npm/lib/node_modules/homebridge/lib/server.js:427:36)
    at Server.<anonymous> (/Users/sgracey/npm/lib/node_modules/homebridge/lib/server.js:413:32)
    at /Users/sgracey/npm/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at Promise.all.then (/Users/sgracey/Code/homebridge-tcc/index.js:92:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

And after accepting the T's and C's via a browser, got this

[9/23/2019, 5:28:00 PM] [Thermostat] Logged into tcc! [ { deviceID: '2077898', name: 'Living Room' } ]
Error _request https://mytotalconnectcomfort.com/portal/Device/CheckDataSession/2077898?_=1569274080800 401
CDS Failed: HTTP Error 401
[9/23/2019, 5:28:00 PM] [Thermostat] Create Device Error HTTP Error 401

**Comment by tekdoc** [comment]
Same here starting today. I have removed tcc platform from my config.json for the time being because it was hanging homebridge.

**Comment by executor485** [comment]
Glad to know it's not just me. The "fix" is to go directly to Honeywell's site: mytotalconnectcomfort.com/ and "accept" the new user agreement. Not sure if there's a workaround for this within homebridge/TCC plugin, but it's definitely a pain in the ***.

**Comment by roberkane212** [comment]
I know this isn’t about this issue, but does anyone know how to enable auto off/on with HomeKit. I don’t get the option just heat, cool, and off

**Comment by NorthernMan54** [comment]
As mine doesn’t support auto, I did not know how code it, so it isn’t implemented

**Comment by roberkane212** [comment]
@nothernman54 thanks for the quick response. Do you know if I’d be able to implement on mine using your plug in? Although I’m very good at writing code so maybe I should just leave as is

**Comment by NorthernMan54** [comment]
Go ahead and give it a try, if you can get it working you can share it as a pull request for everyone else.

PS I’m not thrilled with the code quality of this plugin, as I took someone else’s work and force fit it for this, so it isn’t pretty

**Comment by bemental** [comment]
> @nothernman54 thanks for the quick response. Do you know if I’d be able to implement on mine using your plug in? Although I’m very good at writing code so maybe I should just leave as is

Hey @nothernman5, thought I'd chime in here since we just moved into a rental and it has an older HW thermostat.

If you don't know about the app [Home+ on iOS](https://apps.apple.com/us/app/home-4/id995994352) I highly recommend giving it a try.

Somehow, this app is able to allow you to configure automations that just aren't possible in the native Home app on iOS, and I've found specifically some of the thermostat automation options work well with HomeBridge and this ancient HW thermostat I've been wrestling with.

Let me know if you have any questions!

**Comment by felho001** [comment]
Hi I try use this config but not work for me international tcc suite.
{
"platform": "tcc",
"name": "Thermostat",
"username": "felho001@gmail.com",
"password": "********",
"devices": [
{
"deviceID": "2617502",
"name": "Other Floor",
"usePermanentHolds": true
}
]
}
I have HONEYWELL ATC928 WIFI EVOHOME and
HONEYWELL HR92 (10 pince)
HONEYWELL BDR

**Comment by NorthernMan54** [comment]
@felho001 The international version is not supported by this plugin.
