### ISSUE TITLE
Permanent Holds not working

### ISSUE THREAD

**Issue by drrock77** [NorthernMan54/homebridge-tcc#53]
Hi,

I'm trying to configure the plugin to not use permanent holds on temperature setting events, but it does not seem to work. 
 
I've got the following in my appropriate device block: 
 "usePermanentHolds": false

The temperature is set appropriately, but always on permanent hold. Any ideas? 

Thanks.

**Comment by NorthernMan54** [comment]
Try removing the usePermanentHolds option altogether from the config.json

**Comment by drrock77** [comment]
That did it...thanks.
