### ISSUE TITLE
Emergency Heat option not available.

### ISSUE THREAD

**Issue by Nodak108** [NorthernMan54/homebridge-tcc#54]
I have your Tcc plugin working with a Honeywell TH8321WF1001 and everything seem to work very well. The only issue that I have run across is that the Emergency Heat button does not show, without it this spring the heat pump may try to start before the ice is out of the condenser. Is there something I have missed in setting up the Homebridge or is something else? Thank You for a great plugin.

**Comment by NorthernMan54** [comment]
Emergency heat is not a feature of this plugin
