### ISSUE TITLE
Homebridge-tcc is spamming my homebridge logs.

### ISSUE THREAD

**Issue by jondthompson** [NorthernMan54/homebridge-tcc#58]
Can you please suppress dateless log entries every minute?

[4/29/2020, 3:29:35 PM] [Thermostat] Change Home {}
[4/29/2020, 3:30:35 PM] [Thermostat] updateValues 1

**Comment by NorthernMan54** [comment]
Moved those to debug

Please update to the latest and try again

**Comment by jondthompson** [comment]
Looks much better. Thank you.
