### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by UmmActuallyJP** [NorthernMan54/homebridge-tcc#61]
I changed the info of the sample config, and it says the .json file is wrong/broken. How do I add to to the config?

**Comment by NorthernMan54** [comment]
Please share your config

**Comment by UmmActuallyJP** [comment]
> Please share your config

I used the one from the readme... I just changed it with my info. It says it’s not right. I even tried using a .json verify thing

**Comment by NorthernMan54** [comment]
Without something to look at, their isn't a lot I can share to help

**Comment by UmmActuallyJP** [comment]
Sure, no prob... Like I said, I used this one. With the ....'s changed with my info

"platforms": [
       {
            "platform": "tcc",
            "name" : "Thermostat",
            "username" : ".....",
            "password" : ".....",
            "devices" : [
                  {"deviceID": "1234567", "name": "Other Floor", "usePermanentHolds": true},
                  {"deviceID": "abcdefg", "name": "Main Floor", "usePermanentHolds": false}
          	]
        },
    ]

**Comment by NorthernMan54** [comment]
The last comma is the issue

```
"platforms": [
{
"platform": "tcc",
"name" : "Thermostat",
"username" : ".....",
"password" : ".....",
"devices" : [
{"deviceID": "1234567", "name": "Other Floor", "usePermanentHolds": true},
{"deviceID": "abcdefg", "name": "Main Floor", "usePermanentHolds": false}
]
}
]
```

**Comment by UmmActuallyJP** [comment]
Great, thanks!
