### ISSUE TITLE
can't install plugin on Windows

### ISSUE THREAD

**Issue by paudi112233** [NorthernMan54/homebridge-tcc#67]
Homebridge-TCC was working fine for about 2 weeks. Then it suddenly disappeared from my installed plugins. . I tried to reinstall it but i'm "gettinggyp ERR! find Python".   I'm using home bridge on windows 10. How can i fix this? 

Thanks.

**Comment by NorthernMan54** [comment]
Over the weekend I had made some major updates to the plugin and it appears that one of the modules had a problem installing.  Can you provide a comprehensive error message?

**Comment by paudi112233** [comment]
hope this helps. let me know if you need anything else.

npm WARN deprecated hoek@4.2.1: This version has been deprecated in accordance w
ith the hapi support policy (hapi.im/support). Please upgrade to the latest vers
ion to get the best features, bug fixes, and security patches. If you are unable
 to upgrade at this time, paid support is available for older versions (hapi.im/
commercial).
npm WARN deprecated joi@13.7.0: This version has been deprecated in accordance w
ith the hapi support policy (hapi.im/support). Please upgrade to the latest vers
ion to get the best features, bug fixes, and security patches. If you are unable
 to upgrade at this time, paid support is available for older versions (hapi.im/
commercial).
npm WARN deprecated hoek@5.0.4: This version has been deprecated in accordance w
ith the hapi support policy (hapi.im/support). Please upgrade to the latest vers
ion to get the best features, bug fixes, and security patches. If you are unable
 to upgrade at this time, paid support is available for older versions (hapi.im/
commercial).
npm WARN deprecated topo@3.0.3: This module has moved and is now available at @h
api/topo. Please update your dependencies as this version is no longer maintaine
d an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @h
api/hoek. Please update your dependencies as this version is no longer maintaine
d an may contain bugs and security issues.

> node-expat@2.3.18 install C:\Program Files\nodejs\node_modules\homebridge-tcc\
node_modules\node-expat
> node-gyp rebuild

C:\Program Files\nodejs\node_modules\homebridge-tcc\node_modules\node-expat>if n
ot defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\n
ode_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp
.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_module
s\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration   
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python checking if the py launcher can be used to find Python 2   
gyp ERR! find Python - "py.exe" is not in PATH or produced an error
gyp ERR! find Python checking if Python is C:\Python27\python.exe
gyp ERR! find Python - "C:\Python27\python.exe" could not be run
gyp ERR! find Python checking if Python is C:\Python37\python.exe
gyp ERR! find Python - "C:\Python37\python.exe" could not be run
gyp ERR! find Python
gyp ERR! find Python ********************************************************** 
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,    
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="C:\Path\To\python.exe"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "C:\Path\To\python.exe"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python ********************************************************** 
gyp ERR! find Python
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (C:\Program Files\nodejs\node_modules\np
m\node_modules\node-gyp\lib\find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (C:\Program Files\nodejs\node_modul
es\npm\node_modules\node-gyp\lib\find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_mod
ules\npm\node_modules\node-gyp\lib\find-python.js:225:16)
gyp ERR! stack     at PythonFinder.execFileCallback (C:\Program Files\nodejs\nod
e_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)        
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:273:12)
e_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)        
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:273:12)
e_modules\npm\node_modules\node-gyp\lib\find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:322:5)        
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:273:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js
:84:21)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"       
gyp ERR! cwd C:\Program Files\nodejs\node_modules\homebridge-tcc\node_modules\no
de-expat
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

**Comment by NorthernMan54** [comment]
Tks, looks like the package node-expat has an issue with Windows installation

Googling the error message shows this as the fix

https://github.com/nodejs/node-gyp#installation

**Comment by paudi112233** [comment]
Thanks! I'll give it a try.

**Comment by paudi112233** [comment]
That fixed it. Thanks for your help NorthernMan54!

**Comment by NorthernMan54** [comment]
Tks, I will include this in the README going forward
