### ISSUE TITLE
Showing status as Off

### ISSUE THREAD

**Issue by thechrisreese** [NorthernMan54/homebridge-tcc#70]
Since the new update my Redlink Gateway thermostats all show as Off while the thermostats are clearly On and the mobile app displays them as On. 

Thoughts?

**Comment by thechrisreese** [comment]
Sure it's a long time later - but I tried to set the device to Auto again forgetting why I didn't want to do that before. And here is the debug: 



[3/1/2021, 4:13:57 AM] [Thermostat] Setting switch for Upstairs to 3
Mon, 01 Mar 2021 04:13:57 GMT tcc put 1751468 -> { TargetHeatingCooling: 3 }
Mon, 01 Mar 2021 04:13:57 GMT tcc-lib Queue: Working on item #7.  Size: 0  Pending: 0
Mon, 01 Mar 2021 04:13:57 GMT tcc-lib _UpdateThermostat() { ThermostatID: 1751468, TargetHeatingCooling: 3 }
Mon, 01 Mar 2021 04:13:57 GMT tcc-lib _UpdateThermostat: SOAP Message <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://services.alarmnet.com/Services/MobileV2/"><soap:Body><ChangeThermostatUI><sessionID></sessionID><thermostatID></thermostatID><changeSystemSwitch>1</changeSystemSwitch><systemSwitch>4</systemSwitch><changeHeatSetpoint>1</changeHeatSetpoint><heatSetpoint>70</heatSetpoint><changeCoolSetpoint>1</changeCoolSetpoint><coolSetpoint>78</coolSetpoint><changeHeatNextPeriod>1</changeHeatNextPeriod><heatNextPeriod>88</heatNextPeriod><changeCoolNextPeriod>1</changeCoolNextPeriod><coolNextPeriod>88</coolNextPeriod><changeStatusHeat>1</changeStatusHeat><statusHeat>2</statusHeat><changeStatusCool>1</changeStatusCool><statusCool>2</statusCool></ChangeThermostatUI></soap:Body></soap:Envelope>{ ThermostatID:, TargetHeatingCooling: 3 } {
  ThermostatID:,
  Name: 'Upstairs',
  Model: 'Unknown model',
  OutsideTemperature: '53.9',
  CurrentTemperature: '23.3',
  TargetTemperature: '21.1',
  HeatingThresholdTemperature: '21.1',
  CoolingThresholdTemperature: '25.6',
  CurrentHeatingCoolingState: 0,
  TargetHeatingCoolingState: 3,
  TargetHeatingCoolingStateValidValues: [ 0, 1, 2, 3 ],
  TargetTemperatureHeatMinValue: '4.4',
  TargetTemperatureHeatMaxValue: '32.2',
  TargetTemperatureCoolMinValue: '10.0',
  TargetTemperatureCoolMaxValue: '37.2',
  OutsideHumidity: 129,
  InsideHumidity: 128,
  device: {
    ThermostatID:,
    MacID: '',
    DomainID:,
    Instance: 3,
    DeviceName: 'UPPER LEVEL',
    UserDefinedDeviceName: 'Upstairs',
    Upgrading: false,
    ThermostatsAlerts: {},
    UI: {
      Created: '2021-03-01T04:13:56.1637685',
      ThermostatLocked: false,
      OutdoorTemp: 129,
      DispTemperature: 74,
      HeatSetpoint: 70,
      CoolSetpoint: 78,
      DisplayedUnits: 'F',
      StatusHeat: 2,
      StatusCool: 2,
      HoldUntilCapable: true,
      ScheduleCapable: true,
      VacationHold: 510,
      DualSetpointStatus: false,
      HeatNextPeriod: 88,
      CoolNextPeriod: 88,
      HeatLowerSetptLimit: 40,
      HeatUpperSetptLimit: 90,
      CoolLowerSetptLimit: 50,
      CoolUpperSetptLimit: 99,
      SchedHeatSp: 68,
      SchedCoolSp: 77,
      SystemSwitchPosition: 4,
      CanSetSwitchAuto: true,
      CanSetSwitchCool: true,
      CanSetSwitchOff: true,
      CanSetSwitchHeat: true,
      CanSetSwitchEmergencyHeat: false,
      CanSetSwitchSouthernAway: false,
      Deadband: 3,
      OutdoorHumidity: 129,
      IndoorHumidity: 128,
      Commercial: false,
      SystemSwitchChangeSource: [Object],
      HeatSetpointChangeSource: [Object],
      CoolSetpointChangeSource: [Object]
    },
    Fan: {
      CanControl: false,
      Position: 'Auto',
      CanSetAuto: false,
      CanSetCirculate: false,
      CanFollowSchedule: false,
      CanSetOn: false,
      IsFanRunning: [Object]
    },
    Humidification: {
      CanControlHumidification: false,
      CanControlDehumidification: false,
      HumidificationSetPoint: 0,
      HumidificationUpperLimit: 0,
      HumidificationLowerLimit: 0,
      HumidificationMode: 'Off',
      DehumidificationSetPoint: 0,
      DehumidificationUpperLimit: 0,
      DehumidificationLowerLimit: 0,
      DehumidificationMode: 'Off',
      Deadband: 0
    },
    EquipmentStatus: { 'xsi:nil': true },
    CanControlSchedule: false,
    WillSupportSchedule: false,
    ModelTypeID: 0,
    ModelTypeName: 'Unknown model'
  }
} true
Mon, 01 Mar 2021 04:13:57 GMT tcc-lib Success: _UpdateThermostat { Result: 'Success', CommTaskID: } <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://services.alarmnet.com/Services/MobileV2/"><soap:Body><ChangeThermostatUI><sessionID></sessionID><thermostatID></thermostatID><changeSystemSwitch>1</changeSystemSwitch><systemSwitch>4</systemSwitch><changeHeatSetpoint>1</changeHeatSetpoint><heatSetpoint>70</heatSetpoint><changeCoolSetpoint>1</changeCoolSetpoint><coolSetpoint>78</coolSetpoint><changeHeatNextPeriod>1</changeHeatNextPeriod><heatNextPeriod>88</heatNextPeriod><changeCoolNextPeriod>1</changeCoolNextPeriod><coolNextPeriod>88</coolNextPeriod><changeStatusHeat>1</changeStatusHeat><statusHeat>2</statusHeat><changeStatusCool>1</changeStatusCool><statusCool>2</statusCool></ChangeThermostatUI></soap:Body></soap:Envelope>
Mon, 01 Mar 2021 04:13:58 GMT tcc-lib GetCommTaskState Success {
  Result: 'Success',
  CommTaskID: 1291676810,
  State: 'Running',
  FaultReason: 'GatewayNotFound'
}
Mon, 01 Mar 2021 04:14:22 GMT tcc-lib Queue: Working on item #8.  Size: 0  Pending: 0
Mon, 01 Mar 2021 04:14:23 GMT tcc-lib pollThermostat - delta {
  "LocationInfo": {
    "Thermostats": {
      "ThermostatInfo": {
        "2": {
          "UI": {
            "Created": "2021-03-01T04:13:57.5895597",
            "SystemSwitchPosition": 4
          }
        }
      }
    }
  }
}
Mon, 01 Mar 2021 04:14:23 GMT tcc pollDevices - updateStatus DownstairsHall
Mon, 01 Mar 2021 04:14:23 GMT tcc pollDevices - updateStatus KITCHEN
Mon, 01 Mar 2021 04:14:23 GMT tcc pollDevices - updateStatus Upstairs
Mon, 01 Mar 2021 04:15:22 GMT tcc-lib Queue: Working on item #9.  Size: 0  Pending: 0
Mon, 01 Mar 2021 04:15:23 GMT tcc-lib pollThermostat - delta {
  "LocationInfo": {
    "Thermostats": {
      "ThermostatInfo": {
        "2": {
          "UI": {
            "Created": "2021-03-01T04:15:37",
            "SystemSwitchPosition": 5
          }
        }
      }
    }
  },
  "hb": {
    "1751468": {
      "TargetTemperature": "23.3",
      "TargetHeatingCoolingState": 0,
      "device": {
        "UI": {
          "Created": "2021-03-01T04:15:37",
          "SystemSwitchPosition": 5
        }
      }
    }
  }
}
Mon, 01 Mar 2021 04:15:23 GMT tcc pollDevices - updateStatus DownstairsHall
Mon, 01 Mar 2021 04:15:23 GMT tcc pollDevices - updateStatus KITCHEN
Mon, 01 Mar 2021 04:15:23 GMT tcc pollDevices - updateStatus Upstairs

**Comment by thechrisreese** [comment]
It seems - my particular model has a systemswitchposition of 4 for Auto which is why 3 is throwing it off?

**Comment by johnjensenish** [comment]
I think what's happening is that a `SystemSwitchPosition` of `5` is handled like the device is off, but it's in auto mode. It seems this bug had originally been fixed in #28 has come back.

I am seeing the same issue with my MHK1 thermostats when I set them to "auto".

**Comment by thechrisreese** [comment]
Yes! I couldn't get the log to work but that's exactly it.

**Comment by johnjensenish** [comment]
I've opened up a pull request to fix this bug :)

**Comment by NorthernMan54** [comment]
Tks to @johnjensenish I have published his fixes for this.  Can someone that was experiencing the issues confirm that it is resolved?

**Comment by thechrisreese** [comment]
> Tks to @johnjensenish I have published his fixes for this. Can someone that was experiencing the issues confirm that it is resolved?

Seems to be working!

**Comment by NorthernMan54** [comment]
Tks for confirming

Well done everyone
