### ISSUE TITLE
Sending command to alarmnet.com does not use HTTPS

### ISSUE THREAD

**Issue by TCCson** [NorthernMan54/homebridge-tcc#75]
Hi NorthernMan, thanks very much for writing and continuing to develop this plug in. 

I was wondering if there is a way to send the SOAP commands to http://services.alarmnet.com/Services/MobileV2/ over HTTPS instead of HTTP. I'm uncomfortable with the fact that the information below is being sent in plaintext over the internet.

However, I understand that this may not be possible, because it looks like the alarmnet.com is using an https certificate that expired in 2011.

Please let me know if you have any ideas. Thanks!

    Sat, 20 Jun 2020 21:02:24 GMT tcc-lib Success: _UpdateThermostat { Result: 'Success', CommTaskID: 910961085 } <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns="http://services.alarmnet.com/Services/MobileV2/"><soap:Body><ChangeThermostatUI><sessionID>[UNIQUE SESSION ID]</sessionID><thermostatID>[PRESUMABLY UNIQUE THERMOSTAT ID, BUT POSSIBLY JUST A MODEL ID]</thermostatID><changeSystemSwitch>1</changeSystemSwitch><systemSwitch>3</systemSwitch><changeHeatSetpoint>1</changeHeatSetpoint><heatSetpoint>70</heatSetpoint><changeCoolSetpoint>1</changeCoolSetpoint><coolSetpoint>75</coolSetpoint><changeHeatNextPeriod>1</changeHeatNextPeriod><heatNextPeriod>0</heatNextPeriod><changeCoolNextPeriod>1</changeCoolNextPeriod><coolNextPeriod>0</coolNextPeriod><changeStatusHeat>1</changeStatusHeat><statusHeat>2</statusHeat><changeStatusCool>1</changeStatusCool><statusCool>2</statusCool></ChangeThermostatUI></soap:Body></soap:Envelope>
    Sat, 20 Jun 2020 21:02:25 GMT tcc-lib GetCommTaskState Success {
    Result: 'Success',
    CommTaskID: 910961085,
    State: 'Running',
    FaultReason: 'GatewayNotFound'
    }

**Comment by NorthernMan54** [comment]
If you could find an alternate documented API, please share.  I would gladly change
