### ISSUE TITLE
Feature request: Please add outdoor temperature/humidity as Homekit sensors.

### ISSUE THREAD

**Issue by dbavatar** [NorthernMan54/homebridge-tcc#76]
TCC reports live data if they are configured in your location. For example "Honeywell C7089R1013 Wireless Outdoor Sensor"

**Comment by kylerove** [comment]
I really wanted this to setup temperature-based automations. This isn't possible with just a thermostat in HomeKit, so I started digging into the code. I have both internal and external sensors working and updating based on the TCC data returned.

Additionally, I added configuration parameters to allow users to only show certain sensors by thermostat. For example, I have 3 thermostats and inside and outside temp/humidity is reported for each. I only need one set of outside sensors, so I can set this under the devices.

See my pull request https://github.com/NorthernMan54/homebridge-tcc/pull/91

**Comment by NorthernMan54** [comment]
Tks @kylerove for doing the work on this feature

This has now been published as version 0.2.17
