### ISSUE TITLE
International support

### ISSUE THREAD

**Issue by theobouwman** [NorthernMan54/homebridge-tcc#84]
Is support for international.mytotalconnectcomfort.com planned?

**Comment by NorthernMan54** [comment]
@theobouwman Unless someone wants to take on adding the functionality, unfortunately not.  Device support is limited to what I have access to and use on a regular basis.

Have you looked at the other Honeywell plugins, in case one of them support it?

**Comment by theobouwman** [comment]
@NorthernMan54 which other plugins?
