### ISSUE TITLE
TCC Issue on Hoobs

### ISSUE THREAD

**Issue by sthomas007** [NorthernMan54/homebridge-tcc#85]
I'm getting the following error on Hoobs with the TCC plugin.

[Thermostat] Critical Error - No devices created, please restart.

I have tried everything and I'm not able to get my thermostat to show up in the Home app. I'm not sure what happened because it was working great until about a week or so ago. Any thoughts or suggestions?

**Comment by NorthernMan54** [comment]
Login / account issue ?

**Comment by sthomas007** [comment]
Verified a dozen times. I even tried reseting the PW and reinstalling and configuring with new PW.

-
Steve

**Comment by NorthernMan54** [comment]
Anything in the logs before that?  It is typically pretty chatty, and can be more chatty in DEBUG mode.
