### ISSUE TITLE
Error in Homebridge after installing plugin

### ISSUE THREAD

**Issue by amse** [NorthernMan54/homebridge-tcc#87]
Im fairly new to homebridge but after installing this plug in I'm getting an error. I have attached a screenshot, if anyone is able to provide any assistance it would be much appreciated. Thanks!

<img width="913" alt="Screen Shot 2020-12-04 at 1 00 56 AM" src="https://user-images.githubusercontent.com/75476499/101149451-cede9f80-35d3-11eb-8f80-4757bb22728a.png">
.

**Comment by NorthernMan54** [comment]
That is a very weird error message and am wondering if it is triggered by your environment

What is your OS etc for running homebridge ?

**Comment by amse** [comment]
OpenMediaVault using Docker/Portainer

**Comment by NorthernMan54** [comment]
That is likely the cause, and not a lot I can do for that besides recommend just running this on a RPI.

The error is saying that the package 'node-expat' is failing to install.  You may want to start your google journey their.
