### ISSUE TITLE
Thermostat Validation

### ISSUE THREAD

**Issue by jcgorla-dev** [NorthernMan54/homebridge-tcc#89]
Didn't see any other way to report a validated thermostat for this plugin. 

I've used TCC with Honeywell's Prestige IAQ Thermostat (THX9421R5021WW) and it's accompanying Equipment Interface Module (THM5421R1021) for well over a year.  I issues to report. 

I will be adding a humidifier and dehumidifier in the future and will report how it works with this plugin.

**Comment by NorthernMan54** [comment]
This is perfect or you can always just edit the README.  It will generate a pull request for review and update.

**Comment by jcgorla-dev** [comment]
I should also add that this thermostat requires the Honeywell Redlink Gateway to work with TCC online. I saw the updates to the Readme, thanks for the mention.
