### ISSUE TITLE
pollDevices Error: timeout

### ISSUE THREAD

**Issue by f00fer** [NorthernMan54/homebridge-tcc#90]
Just a minor issue that's been showing up in my logs.

`pollDevices Error: timeout of 5000ms exceeded`

Due to covid overload of already shaky rural internet, five seconds isn't really cutting it at peak times.  The thermostat seems to go offline after a few timeouts.  After changing "this.timeout = 5000; // SOAP request timeout" to 8000 in tcc.js, the issue seems to go away.   Any chance of making the timeout a configuration option whenever the next release comes out?  Thanks!

**Comment by anonymous-tech-user** [comment]
>  After changing "this.timeout = 5000; // SOAP request timeout" to 8000 in tcc.js, the issue seems to go away. 

I’m also seeing this error, I too get a similar timeout error. You said you were able to change it manually to 8000ms, how can this be achieved? I’m just simply using the plugin, but not sure how to set this setting.

**Comment by f00fer** [comment]
To change it you'll need to connect with SSH, as it's all done on the command line. You need to edit the tcc.js file. Mine was in /usr/lib/node_modules/homebridge-tcc/lib. I'm using Domoticz on Debian. Not sure if it's in the same place on a Pi, Hass, HAB or whatever system you're using.

So for me it was
```
cd /usr/lib/node_modules/homebridge-tcc/lib
sudo nano tcc.js
```
Scroll down to "this.timeout = 5000; // SOAP request timeout",  change it to 8000 and save the file. 1000 = 1 second. 8000 = 8 seconds. Restart homebridge and you're done.

**Comment by anonymous-tech-user** [comment]
Wow, thank you! The in-depth tutorial really helped a lot, hope it doesn’t fail now!

**Comment by nriley** [comment]
I also ran into this, which I suspect may be causing the HomeKit device to disappear. My Internet is pretty decent so I wonder if some of this is on the server end.

```
[3/8/2021, 7:06:17 PM] [Total Connect Comfort] Critical Error - No devices created, please restart.                                                             
[3/8/2021, 7:06:17 PM] [Total Connect Comfort] Error: timeout of 5000ms exceeded
  tcc-lib Queue: Working on item #2.  Size: 0  Pending: 0 +1m                   
[3/8/2021, 7:07:17 PM] [Total Connect Comfort] pollDevices Error: timeout of 5000ms exceeded                                                                    
  tcc-lib Queue: Working on item #3.  Size: 0  Pending: 0 +1m                   
  tcc-lib TCC - Login Succeeded +2s                                             
[3/8/2021, 7:08:19 PM] [Total Connect Comfort] pollDevices Error: timeout of 5000ms exceeded
  tcc-lib Queue: Working on item #4.  Size: 0  Pending: 0 +58s
[3/8/2021, 7:09:17 PM] [Total Connect Comfort] pollDevices Error: timeout of 5000ms exceeded
  tcc-lib Queue: Working on item #5.  Size: 0  Pending: 0 +1m
  tcc-lib TCC - Login Succeeded +2s
  tcc-lib Queue: Working on item #6.  Size: 0  Pending: 0 +58s
[3/8/2021, 7:11:17 PM] [Total Connect Comfort] pollDevices Error: timeout of 5000ms exceeded
```

If I try to restart homebridge after the retries as above it seems I am getting throttled.
```
[3/8/2021, 7:11:39 PM] [Total Connect Comfort] Critical Error - No devices created, please restart.
[3/8/2021, 7:11:39 PM] [Total Connect Comfort] Error: TooManyAttempt
```

I lengthened the timeout as above but it didn't initially help:

```
[3/8/2021, 7:14:38 PM] [Total Connect Comfort] Critical Error - No devices created, please restart.
[3/8/2021, 7:14:38 PM] [Total Connect Comfort] Error: timeout of 10000ms exceeded
```

Finally restarting for a 3rd time it did work:

```
  tcc-lib TCC - Login Succeeded +8s
  tcc Creating accessory for [...]([...]) +6s
  tcc createInsideSensors:  true +1ms
[3/8/2021, 7:15:43 PM] [Total Connect Comfort] Adding TCC Device (deviceID=[...]) [...]
  tcc TccAccessory() [...] InsideTemperature = true, existing sensor +2ms
  tcc TccAccessory() [...] insideHumidity = true, existing sensor +0ms
```

I set the timeout to 60 seconds and will see how it goes. I've never needed to babysit homebridge-tcc like this before though…

**Comment by NorthernMan54** [comment]
I'm having similar issues with my implementation as well.  I'm thinking something changed on the Honeywell side and we are hitting a new rate limiter or something.  I changed the refresh to 300 on my setup today to try and work thru.

**Comment by NorthernMan54** [comment]
Ran for 12 hours last night with refresh set to 300 and had a couple of repeats.  Changed refresh to 600 ( 10 minutes ) and trying again.

**Comment by nriley** [comment]
No problems overnight with timeout of 60 seconds, for what it's worth.

**Comment by NorthernMan54** [comment]
Saw this note in the FAQ for a different Honeywell API, https://developer.honeywellhome.com/faq-page#n76, what stats maximum refresh rate is every 5 minutes.

The plugin was defaulting to 60 second refresh, which exceeds this and triggering the issue. 

@jguyca We are tracking the tweaks needed to timeout and refresh here

The current plugin version has these defaults, 10 seconds for request timeout and data refresh at 5 minutes.

**Comment by NorthernMan54** [comment]
@nriley @jguyca 24 hours of 10 minute refresh and no timeouts.  I think that is the secret.

Going to let this run for the next few days, then republish with the minimum values updated.

**Comment by nriley** [comment]
Same, things have been running smoothly for me for >24 hours at this point with the latest changes (I reverted the timeout changes).

**Comment by NorthernMan54** [comment]
Same for me, so I'm going to republish with 10 minutes as the default forward for refresh and 10 seconds for request timeout.

**Comment by joshstubble** [comment]
It might also be helpful for some to try and run tcc on the main bridge. I was running tcc in a child bridge and no matter what I tried, could not get the polling error to stop. After updating to newest release **and** putting it back on main bridge has it been running very well for me. 

Just what I've been experiencing and it seems a lot of people use child bridges

**Comment by joshstubble** [comment]
Also switched polling to 30 min has helped with timeouts

**Comment by NorthernMan54** [comment]
In my personal setup, running in a child bridge, I am still getting the occasional timeout ( almost daily when I override the schedule to turn the heat on during the day. ( I'm still running the pre-covid WFH thermostat program, keep thinking that we would be going back to normal soon )).

When I get some free time, need to dig in further.

**Comment by joshstubble** [comment]
I've been running tcc on main bridge now for about a week now and it's been running perfect. All automated tasks are completed with no timeouts. I *rarely* will get a "no connection" on the thermostat icon, but if I force press it the error immediately goes away and acts normal. When I was on child bridge, even force pressing it did nothing. 

Also the polling at 30 minutes has seemed to help but I'm not sure if it's one or the other or both.

**Comment by anonymous-tech-user** [comment]
For a couple days, I’ve been getting “no response” in HomeKit but pressing it makes it go away and gets me the right status. It seems as if it is not updating unless I manually click on it. There are no logs with Debug mode off but with it on, I don’t notice anything odd either.

**Comment by joshstubble** [comment]
I've been running tcc on main bridge now for over two weeks and have had zero problems. I am even polling every 30 seconds and still running fine.
