### ISSUE TITLE
Login Succeeded, but getting 'ThermostatID undefined' error

### ISSUE THREAD

**Issue by Zacknetic** [NorthernMan54/homebridge-tcc#95]
Hello,

I have recently purchased a Honeywell RTH6500WF Thermostat. While not explicitly stated to be tested in the readme, it does use the North American "Total Connect Comfort" site. https://www.mytotalconnectcomfort.com/portal

Here are the logs

`Mon, 01 Mar 2021 06:53:43 GMT tcc-lib TCC - Login Succeeded
[01/03/2021, 06:53:44] [Thermostat] Critical Error - No devices created, please restart.
[01/03/2021, 06:53:44] [Thermostat] TypeError: Cannot read property 'ThermostatID' of undefined
Mon, 01 Mar 2021 06:54:41 GMT tcc-lib Queue: Working on item #2.  Size: 0  Pending: 0
Mon, 01 Mar 2021 06:54:41 GMT tcc-lib TCC - Login Succeeded
[01/03/2021, 06:54:42] [Thermostat] pollDevices TypeError: Cannot read property 'ThermostatID' of undefined`

And here is my config which has been generated by the config.schema

{
    "bridge": {
        "name": "Homebridge",
        "username": "xxx",
        "port": 51286,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Thermostat",
            "username": "abc@xyz.com",
            "password": "123456789",
            "refresh": 60,
            "storage": "fs",
            "debug": true,
            "platform": "tcc"
        }
    ]
}

Just curious if I have set something up incorrectly or if this device simply doesn't play nice with this plugin. Let me know if you need anything else. Thank you!

**Comment by NorthernMan54** [comment]
Closing as Zack indicated it was an account issue with his TCC account
